### ISSUE TITLE
Top level build is failing with undefined reference

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/Fuser#103]
```C++
[ 89%] Linking CXX executable nvfuser_tests
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/csrc/kernel_db/test/test_nvfuser_kernel_db_open.cpp.o: in function `nvfuser::NVFuserTest_KernelDb_Open_CUDA_Test::TestBody()':
test_nvfuser_kernel_db_open.cpp:(.text+0x384c): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_nvfuser_kernel_db_open.cpp:(.text+0x3a02): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_nvfuser_kernel_db_open.cpp:(.text+0x3b5f): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_nvfuser_kernel_db_open.cpp:(.text+0x3c8a): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_nvfuser_kernel_db_open.cpp:(.text+0x3e31): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/csrc/kernel_db/test/test_nvfuser_kernel_db_open.cpp.o:test_nvfuser_kernel_db_open.cpp:(.text+0x3f82): more undefined references to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)' follow
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/main.cpp.o: in function `add_negative_flag(std::string const&)':
main.cpp:(.text+0x2b): undefined reference to `testing::FLAGS_gtest_filter'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/main.cpp.o: in function `main':
main.cpp:(.text+0x1c3): undefined reference to `testing::FLAGS_gtest_filter'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu1.cpp.o: in function `testing::internal::PrintTo(std::string const&, std::ostream*)':
test_gpu1.cpp:(.text._ZN7testing8internal7PrintToERKSsPSo[_ZN7testing8internal7PrintToERKSsPSo]+0x23): undefined reference to `testing::internal::PrintStringTo(std::string const&, std::ostream*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu1.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<std::string, std::string>(char const*, char const*, std::string const&, std::string const&)':
test_gpu1.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureISsSsEENS_15AssertionResultEPKcS4_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureISsSsEENS_15AssertionResultEPKcS4_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu2.cpp.o: in function `nvfuser::NVFuserTest_FusionParallelDimensionMap3_CUDA_Test::TestBody()':
test_gpu2.cpp:(.text+0x9315b): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_gpu2.cpp:(.text+0x933b2): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu2.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<c10::optional<long>, int>(char const*, char const*, c10::optional<long> const&, int const&)':
test_gpu2.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureIN3c108optionalIlEEiEENS_15AssertionResultEPKcS7_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureIN3c108optionalIlEEiEENS_15AssertionResultEPKcS7_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `nvfuser::NVFuserMultithreadedTest_SingleFunction_CUDA_Test::TestBody()::{lambda()#1}::operator()() const':
test_gpu3.cpp:(.text+0x38f88): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `nvfuser::NVFuserMultithreadedTest_MultipleFunctions_CUDA_Test::TestBody()::{lambda()#1}::operator()() const':
test_gpu3.cpp:(.text+0x39b9e): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `nvfuser::NVFuserTest_FusionIssue2074_CUDA_Test::TestBody()':
test_gpu3.cpp:(.text+0x781f9): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `nvfuser::NVFuserTest_FusionIssue2077_CUDA_Test::TestBody()':
test_gpu3.cpp:(.text+0x78c2d): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `nvfuser::NVFuserTest_FusionIssue2372_CUDA_Test::TestBody()':
test_gpu3.cpp:(.text+0x79b4f): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o:test_gpu3.cpp:(.text+0x79cb2): more undefined references to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)' follow
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `testing::AssertionResult::AppendMessage(testing::Message const&)':
test_gpu3.cpp:(.text._ZN7testing15AssertionResult13AppendMessageERKNS_7MessageE[_ZN7testing15AssertionResult13AppendMessageERKNS_7MessageE]+0x8a): undefined reference to `testing::Message::GetString() const'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<c10::ScalarType, c10::ScalarType>(char const*, char const*, c10::ScalarType const&, c10::ScalarType const&)':
test_gpu3.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureIN3c1010ScalarTypeES3_EENS_15AssertionResultEPKcS6_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureIN3c1010ScalarTypeES3_EENS_15AssertionResultEPKcS6_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<std::vector<nvfuser::Val*, std::allocator<nvfuser::Val*> >, std::vector<nvfuser::Val*, std::allocator<nvfuser::Val*> > >(char const*, char const*, std::vector<nvfuser::Val*, std::allocator<nvfuser::Val*> > const&, std::vector<nvfuser::Val*, std::allocator<nvfuser::Val*> > const&)':
test_gpu3.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureISt6vectorIPN7nvfuser3ValESaIS5_EES7_EENS_15AssertionResultEPKcSA_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureISt6vectorIPN7nvfuser3ValESaIS5_EES7_EENS_15AssertionResultEPKcSA_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<nvfuser::Val*, nvfuser::Val*>(char const*, char const*, nvfuser::Val* const&, nvfuser::Val* const&)':
test_gpu3.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureIPN7nvfuser3ValES4_EENS_15AssertionResultEPKcS7_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureIPN7nvfuser3ValES4_EENS_15AssertionResultEPKcS7_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu3.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<unsigned long, long>(char const*, char const*, unsigned long const&, long const&)':
test_gpu3.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureImlEENS_15AssertionResultEPKcS4_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureImlEENS_15AssertionResultEPKcS4_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_expr_simplifier.cpp.o: in function `nvfuser::ExprSimplifierTest_Compare_CUDA_Test::TestBody()':
test_expr_simplifier.cpp:(.text+0xe8c0): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_expr_simplifier.cpp:(.text+0xe9fe): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_expr_simplifier.cpp:(.text+0xeb3c): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_expr_simplifier.cpp:(.text+0xec74): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test_expr_simplifier.cpp:(.text+0xedb3): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_expr_simplifier.cpp.o:test_expr_simplifier.cpp:(.text+0xeeeb): more undefined references to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)' follow
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_expr_simplifier.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<std::string, char [98]>(char const*, char const*, std::string const&, char const (&) [98])':
test_expr_simplifier.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureISsA98_cEENS_15AssertionResultEPKcS5_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureISsA98_cEENS_15AssertionResultEPKcS5_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_expr_simplifier.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<std::string, char [30]>(char const*, char const*, std::string const&, char const (&) [30])':
test_expr_simplifier.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureISsA30_cEENS_15AssertionResultEPKcS5_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureISsA30_cEENS_15AssertionResultEPKcS5_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_expr_simplifier.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<c10::optional<bool>, bool>(char const*, char const*, c10::optional<bool> const&, bool const&)':
test_expr_simplifier.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureIN3c108optionalIbEEbEENS_15AssertionResultEPKcS7_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureIN3c108optionalIbEEbEENS_15AssertionResultEPKcS7_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/usr/bin/ld: CMakeFiles/nvfuser_tests.dir/test/test_gpu_swizzle.cpp.o: in function `testing::AssertionResult testing::internal::CmpHelperEQFailure<std::vector<int, std::allocator<int> >, std::vector<int, std::allocator<int> > >(char const*, char const*, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&)':
test_gpu_swizzle.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureISt6vectorIiSaIiEES4_EENS_15AssertionResultEPKcS7_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureISt6vectorIiSaIiEES4_EENS_15AssertionResultEPKcS7_RKT_RKT0_]+0x7f): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/nvfuser_tests.dir/build.make:614: nvfuser_tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:407: CMakeFiles/nvfuser_tests.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    main()
  File "setup.py", line 234, in main
    cmake()
  File "setup.py", line 229, in cmake
    subprocess.check_call(cmd_str)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--target', 'install', '--', '-j', '64']' returned non-zero exit status 2.
```

**Comment by zasdfgbnm** [comment]
cc @jjsjann123

**Comment by jjsjann123** [comment]
I opened an upstream issue to track that. Let's keep this one open as well and we can verify the fix afterwards.

**Comment by jjsjann123** [comment]
linking all the issues: https://github.com/pytorch/pytorch/issues/98093
