### ISSUE TITLE
codegen issue with transformed allocation domain: inferAndValidateAllocationSizesAndStrides triggers std::__throw_bad_variant_access

### ISSUE THREAD

**Issue by jjsjann123** [NVIDIA/Fuser#1048]
Running into this issue while trying to work out a cpp test for #1033 

```
TEST_F(NVFuserTest, IsThisAValidFusion) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion* fusion = fusion_ptr.get();
  FusionGuard fg(fusion);

  std::vector<IterDomain*> domain(3, nullptr);
  for (auto i : c10::irange(3)) {
    domain[i] =
      IterDomainBuilder(
          FusionGuard::getCurFusion()->zeroVal(),
          IrBuilder::create<Val>(DataType::Index))
          .build();
  }

  IterDomain* merged_id =
      IterDomainBuilder(fusion->zeroVal(), mul(domain[0]->extent(), domain[1]->extent())).build();
  IrBuilder::create<Merge>(domain[0]->container(), merged_id, domain[0], domain[1]);

  std::vector<IterDomain*> rfactor_domain = {merged_id, domain[2]};
  std::vector<IterDomain*> alloc_domain = {domain[2], domain[0], domain[1]};
  std::vector<std::optional<bool>> contiguity = {false, true, true};

  auto tv0 = IrBuilder::create<TensorView>(
    IrBuilder::create<TensorDomain>(domain, rfactor_domain, alloc_domain, rfactor_domain, contiguity), DataType::Float);
  fusion->addInput(tv0);

  auto s0 = IrBuilder::create<Val>(5, DataType::Float);
  auto tv1 = add(tv0, s0);
  fusion->addOutput(tv1);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({8, 8}, options).as_strided({4, 4}, {1, 8});
  FusionExecutorCache fec(std::move(fusion_ptr));
  auto outputs = fec.runFusionWithInputs({t0});

  auto t1 = t0.add(5.0);
  testValidate(fusion, outputs, {t0}, {t1}, __LINE__, __FILE__);
}
```

```
Thread 1 "nvfuser_tests" hit Catchpoint 1 (exception thrown), 0x00007fff9515b4a1 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007fff9515b4a1 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000555555978e56 in std::__throw_bad_variant_access (
    __what=0x555556336068 "std::get: wrong index for variant") at /usr/include/c++/11/variant:1314
#2  0x0000555555978e8d in std::__throw_bad_variant_access (__valueless=false)
    at /usr/include/c++/11/variant:1322
#3  0x000055555598994c in std::get<7ul, std::monostate, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>, std::allocator<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool> > > > (
    __v=std::variant<std::monostate, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>>> [index 0] = {...}) at /usr/include/c++/11/variant:1703
#4  0x000055555598233d in std::get<long, std::monostate, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>, std::allocator<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool> > > > (
    __v=std::variant<std::monostate, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>>> [index 0] = {...}) at /usr/include/c++/11/variant:1141
#5  0x000055555597cb10 in dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>::as<long, void> (this=0x7fffffffc618)
    at /opt/pytorch/nvfuser/lib/dynamic_type/src/dynamic_type/dynamic_type.h:162
#6  0x00007ffff760ac28 in nvfuser::(anonymous namespace)::BackwardTraverseFromRFactorToAlloc::handle (
    this=0x7fffffffc4a0, merge=0x55555ad10700) at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:157
#7  0x00007ffff760af69 in nvfuser::(anonymous namespace)::BackwardTraverseFromRFactorToAlloc::handle (
    this=0x7fffffffc4a0, expr=0x55555ad10700) at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:187
#8  0x00007ffff760b1e6 in nvfuser::(anonymous namespace)::BackwardTraverseFromRFactorToAlloc::run (
    this=0x7fffffffc4a0, tv=0x55555a0ba8b0, rfactor=std::vector of length 2, capacity 2 = {...},
    alloc=std::vector of length 3, capacity 4 = {...})
    at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:209
#9  0x00007ffff760bca8 in nvfuser::(anonymous namespace)::inferAndValidateAllocationSizesAndStrides (
    tensor=..., tv=0x55555a0ba8b0, ee=...) at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:312
#10 0x00007ffff760c314 in nvfuser::GetMetaData::evaluate (this=0x55555ad19620, ee=...,
    inputs=std::vector of length 1, capacity 1 = {...})
    at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:356
#11 0x00007ffff6e4b364 in nvfuser::ExpressionEvaluator::evaluateHelper (this=0x55555a5f5f60,
    value=0x55555ad19520, known_values=std::unordered_map with 3 elements = {...})
    at /opt/pytorch/nvfuser/csrc/expr_evaluator.cpp:201
#12 0x00007ffff6e4afdf in nvfuser::ExpressionEvaluator::evaluate (this=0x55555a5f5f60,
    value=0x55555ad19520) at /opt/pytorch/nvfuser/csrc/expr_evaluator.cpp:170
#13 0x00007ffff754a66a in nvfuser::SchedulerRuntimeInfo::SchedulerRuntimeInfo (this=0x7fffffffca10,
    complete_fusion=0x555559f9e5f0, args=..., precomputed_values=0x0,
    all_tvs=std::vector of length 2, capacity 2 = {...},
    forced_index_type=std::optional<nvfuser::PrimDataType> [no contained value])
    at /opt/pytorch/nvfuser/csrc/scheduler/registry.cpp:49
#14 0x00007ffff7169798 in nvfuser::FusionKernelRuntime::FusionKernelRuntime (this=0x55555a1d1350,
    fusion=std::unique_ptr<nvfuser::Fusion> = {...}, args=...,
    forced_index_type=std::optional<nvfuser::PrimDataType> [no contained value])
    at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:909
```

**Comment by kevinstephano** [comment]
@jjsjann123 it looks like there was PR fixing this issue, can it be closed?

**Comment by jjsjann123** [comment]
I think I need to close this. As the way that we specify allocation domain isn't on the path between logical to loop. So this might not be considered as a legit fusion.

```
  IterDomain* merged_id =
      IterDomainBuilder(fusion->zeroVal(), mul(domain[0]->extent(), domain[1]->extent())).build();
  IrBuilder::create<Merge>(domain[0]->container(), merged_id, domain[0], domain[1]);
```
