### ISSUE TITLE
"IndexError: _Map_base::at" with scalar output

### ISSUE THREAD

**Issue by IvanYashchuk** [NVIDIA/Fuser#1172]
Reproducer:
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    S0 = fd.define_scalar(None, dtype=DataType.Double)
    S1 = fd.define_scalar(None, dtype=DataType.Double)
    T2 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    T3 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    S4 = fd.define_scalar(1.41421, dtype=DataType.Double)
    S5 = fd.ops.reciprocal(S4)
    T6 = fd.ops.mul(T3, S5)
    T7 = fd.ops.erf(T6)
    S8 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T9 = fd.ops.mul(S8, T7)
    S10 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T11 = fd.ops.add(S10, T9)
    T12 = fd.ops.mul(T2, T11)
    T13 = fd.ops.mul(T2, T3)
    S14 = fd.define_scalar(1.00000, dtype=DataType.Double)
    T15 = fd.ops.mul(S14, T13)
    T16 = fd.ops.mul(T15, S1)
    S17 = fd.define_scalar(2.00000, dtype=DataType.Double)
    T18 = fd.ops.mul(T16, S17)
    S19 = fd.define_scalar(3.14159, dtype=DataType.Double)
    S20 = fd.ops.sqrt(S19)
    S21 = fd.ops.reciprocal(S20)
    T22 = fd.ops.mul(T18, S21)
    T23 = fd.ops.neg(T6)
    T24 = fd.ops.mul(T23, T6)
    T25 = fd.ops.exp(T24)
    T26 = fd.ops.mul(T22, T25)
    S27 = fd.ops.reciprocal(S0)
    T28 = fd.ops.mul(T26, S27)
    T29 = fd.ops.add(T12, T28)
    fd.add_output(S20)
    fd.add_output(T29)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    1.4142135623730951,
    0.5,
    torch.randn((44800,), dtype=torch.float32, device='cuda:0').as_strided((5, 5, 1792), (8960, 1792, 1)),
    torch.randn((44800,), dtype=torch.float32, device='cuda:0').as_strided((5, 5, 1792), (8960, 1792, 1)),
]
fd.execute(inputs)
```
```py
Traceback (most recent call last):
  File "/home/iyashchuk/dev/nvfuser/nvfuser/__init__.py", line 123, in execute
    result = self._execute(
IndexError: _Map_base::at
```

**Comment by IvanYashchuk** [comment]
It would be good to at least return a more informative error message that returning CPU scalars is not supported.

**Comment by naoyam** [comment]
@wujingyue Could you take a look? I suppose we would just need to give a more informative error message.

**Comment by wujingyue** [comment]
`fd.add_output(S20)` triggered the error. I'll send out a PR to print the missing key soon. 

My first suspicion was that this is due to my recent cleanup PRs (#1141 and #1150). After I `git revert` them, I got a different error -- can't cast a scalar to TensorView. This means #1141 and #1150 are indeed related but not the culprits. 

```
Thread 1 "python" hit Catchpoint 1 (exception thrown), 0x00007ffff6c824a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff6c824a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007fff10881e90 in nvfuser::nvfCheckFail (func=0x7fff11030582 "as", file=0x7fff11030560 "/opt/pytorch/nvfuser/csrc/utils.h", line=101,
    msg=0x7fff110304a8 "downcast_ptr != nullptr INTERNAL ASSERT FAILED at \"/opt/pytorch/nvfuser/csrc/utils.h\":101, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. ") at /opt/pytorch/nvfuser/csrc/exceptions.cpp:281
#2  0x00007fff106c3e0d in nvfuser::nvfErrorFail (func=0x7fff11030582 "as", file=0x7fff11030560 "/opt/pytorch/nvfuser/csrc/utils.h", line=101,
    condMsg=0x7fff110304a8 "downcast_ptr != nullptr INTERNAL ASSERT FAILED at \"/opt/pytorch/nvfuser/csrc/utils.h\":101, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. ") at /opt/pytorch/nvfuser/csrc/exceptions.h:214
#3  0x00007fff106c810d in nvfuser::PolymorphicBase::as<nvfuser::TensorView> (this=0x55555b27f3c0) at /opt/pytorch/nvfuser/csrc/utils.h:101
#4  0x00007fff10ab0efd in nvfuser::FusionKernelRuntime::runWithInputs (this=0x55555b2663d0, args=...) at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:1249
#5  0x00007fff10aab654 in nvfuser::FusionExecutorCache::runFusionWithInputs (this=0x55555acdbdf0, inputs=..., forced_index_type=std::optional<nvfuser::PrimDataType> [no contained value],
    selected_device=std::optional<signed char> [no contained value]) at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:490
#6  0x00007fff10fa655c in nvfuser::python_frontend::FusionDefinition::execute (this=0x55555acda790, inputs=..., override_user_schedule=false, capture_debug_output=false,
    selected_device=std::optional<signed char> [no contained value]) at /opt/pytorch/nvfuser/csrc/python_frontend/fusion_definition.cpp:180
#7  0x00007fff118fab3e in pybind11::cpp_function::initialize<nvfuser::python_frontend::initNvFuserPythonBindings(_object*)::{lambda(nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, bool, std::optional<long>, bool)#16}, std::vector<at::Tensor, std::allocator<at::Tensor> >, nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, bool, std::optional<long>, bool, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::kw_only, pybind11::arg_v, pybind11::arg_v, pybind11::return_value_policy>(nvfuser::python_frontend::initNvFuserPythonBindings(_object*)::{lambda(nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, bool, std::optional<long>, bool)#16}&&, std::vector<at::Tensor, std::allocator<at::Tensor> > (*)(nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, bool, std::optional<long>, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::kw_only const&, pybind11::arg_v const&, pybind11::arg_v const&, pybind11::return_value_policy const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) ()
   from /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#8  0x00007fff1197af37 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#9  0x00005555556a3cbb in cfunction_call (func=0x7fff1329e930, args=<optimized out>, kwargs=<optimized out>) at Objects/methodobject.c:543
#10 0x000055555569d6ab in _PyObject_MakeTpCall (tstate=0x55555591c000, callable=0x7fff1329e930, args=<optimized out>, nargs=<optimized out>, keywords=0x7fff11a71840) at Objects/call.c:215
#11 0x00005555556af60f in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=0x55555acd91b8, callable=0x7fff1329e930, tstate=0x55555591c000) at ./Include/cpython/abstract.h:112
#12 _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=0x55555acd91b8, callable=0x7fff1329e930, tstate=0x55555591c000) at ./Include/cpython/abstract.h:99
#13 method_vectorcall (method=<optimized out>, args=0x55555acd91c0, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/classobject.c:53
#14 0x000055555569457c in _PyObject_VectorcallTstate (kwnames=0x7fff11a71840, nargsf=<optimized out>, args=<optimized out>, callable=0x7fff125e2200, tstate=0x55555591c000) at ./Include/cpython/abstract.h:114
#15 PyObject_Vectorcall (kwnames=0x7fff11a71840, nargsf=<optimized out>, args=<optimized out>, callable=0x7fff125e2200) at ./Include/cpython/abstract.h:123
#16 call_function (kwnames=0x7fff11a71840, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7fffffffd3d0, tstate=<optimized out>) at Python/ceval.c:5893
#17 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x55555acd8fe0, throwflag=<optimized out>) at Python/ceval.c:4231
#18 0x00005555556a4123 in _PyEval_EvalFrame (throwflag=0, f=0x55555acd8fe0, tstate=0x55555591c000) at ./Include/internal/pycore_ceval.h:46
#19 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7fff11ac3e30, tstate=0x55555591c000) at Python/ceval.c:5067
#20 _PyFunction_Vectorcall (func=0x7fff11ac3e20, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:342
#21 0x00005555556937de in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff7b75ba8, callable=0x7fff11ac3e20, tstate=0x55555591c000) at ./Include/cpython/abstract.h:114
#22 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff7b75ba8, callable=0x7fff11ac3e20) at ./Include/cpython/abstract.h:123
#23 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7fffffffd590, tstate=<optimized out>) at Python/ceval.c:5893
#24 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7ffff7b75a40, throwflag=<optimized out>) at Python/ceval.c:4198
#25 0x0000555555741522 in _PyEval_EvalFrame (throwflag=0, f=0x7ffff7b75a40, tstate=0x55555591c000) at ./Include/internal/pycore_ceval.h:46
#26 _PyEval_Vector (tstate=0x55555591c000, con=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:5067
#27 0x000055555574146f in PyEval_EvalCode (co=co@entry=0x7ffff7acea20, globals=globals@entry=0x7ffff7a8e000, locals=locals@entry=0x7ffff7a8e000) at Python/ceval.c:1134
#28 0x000055555575182c in run_eval_code_obj (tstate=0x55555591c000, co=0x7ffff7acea20, globals=0x7ffff7a8e000, locals=0x7ffff7a8e000) at Python/pythonrun.c:1291
#29 0x000055555574cdc4 in run_mod (mod=<optimized out>, filename=<optimized out>, globals=0x7ffff7a8e000, locals=0x7ffff7a8e000, flags=<optimized out>, arena=<optimized out>) at Python/pythonrun.c:1312
#30 0x00005555555f0a32 in pyrun_file (fp=fp@entry=0x5555558ff370, filename=filename@entry=0x7ffff7ac9750, start=start@entry=257, globals=globals@entry=0x7ffff7a8e000, locals=locals@entry=0x7ffff7a8e000,
    closeit=closeit@entry=1, flags=0x7fffffffd888) at Python/pythonrun.c:1208
#31 0x00005555555f0680 in _PyRun_SimpleFileObject (fp=0x5555558ff370, filename=0x7ffff7ac9750, closeit=1, flags=0x7fffffffd888) at Python/pythonrun.c:456
#32 0x00005555555f2928 in _PyRun_AnyFileObject (fp=0x5555558ff370, filename=filename@entry=0x7ffff7ac9750, closeit=closeit@entry=1, flags=flags@entry=0x7fffffffd888) at Python/pythonrun.c:90
#33 0x000055555575e27d in pymain_run_file_obj (skip_source_first_line=0, filename=0x7ffff7ac9750, program_name=0x7ffff7ac97f0) at Modules/main.c:353
#34 pymain_run_file (config=0x5555559005f0) at Modules/main.c:372
#35 pymain_run_python (exitcode=0x7fffffffd880) at Modules/main.c:587
#36 Py_RunMain () at Modules/main.c:666
#37 0x000055555573143d in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:720
#38 0x00007ffff7cced90 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#39 0x00007ffff7ccee40 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#40 0x0000555555731325 in _start ()
(gdb) f 4
#4  0x00007fff10ab0efd in nvfuser::FusionKernelRuntime::runWithInputs (this=0x55555b2663d0, args=...) at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:1249
1249          auto out_tv = output->as<TensorView>();
(gdb) l
1244        } else {
1245          bool empty_type_check = output->getDataType().has_value() &&
1246              output->getDataType().value() == DataType::Float;
1247
1248          // Only support two cases of empty tensor here, since this is hot path.
1249          auto out_tv = output->as<TensorView>();
1250
1251          // TODO: should be only one of the two once the "empty"
1252          //  definition has been unified throughout the ops.
1253          bool empty_tensor_check = out_tv->isZeroDim() || out_tv->isEmptyTensor();
(gdb) p output->toString(0)
$2 = "d80"
```

So, apparently, we have problems dealing with scalar outputs. One suspicion is that we skip scalar outputs when building initial segments: https://github.com/NVIDIA/Fuser/blob/bce26ef4589066bd9765cea2ca61254031cd26a3/csrc/fusion_segmenter.cpp#L3297-L3299. Keep looking...

**Comment by naoyam** [comment]
I thought this was just because we don't support scalar fusion outputs at this moment. So, we should just throw an error when a scalar is specified as a fusion output.
