### ISSUE TITLE
Group norm concretization error

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#1411]
The following group norm example encounters an error:

```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id12(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False)
    S1 = fd.define_scalar(None, dtype=DataType.Double)
    S2 = fd.define_scalar(None, dtype=DataType.Int)
    S3 = fd.define_scalar(2, dtype=DataType.Int)
    S4 = fd.define_scalar(1, dtype=DataType.Int)
    S5 = fd.define_scalar(2, dtype=DataType.Int)
    V6 = fd.define_vector([S3, S4, S5], dtype=DataType.Int)
    T7 = fd.ops.reshape(T0, new_shape=V6)
    T8, T9 = fd.ops.var_mean(T7, axes=[2], correction=0, keepdim=False)
    S10 = fd.define_scalar(2, dtype=DataType.Int)
    S11 = fd.define_scalar(1, dtype=DataType.Int)
    S12 = fd.define_scalar(1, dtype=DataType.Int)
    V13 = fd.define_vector([S10, S11, S12], dtype=DataType.Int)
    T14 = fd.ops.broadcast_in_dim(T8, shape=V13, broadcast_dims=[0, 1])
    S15 = fd.define_scalar(2, dtype=DataType.Int)
    S16 = fd.define_scalar(1, dtype=DataType.Int)
    S17 = fd.define_scalar(1, dtype=DataType.Int)
    V18 = fd.define_vector([S15, S16, S17], dtype=DataType.Int)
    T19 = fd.ops.broadcast_in_dim(T9, shape=V18, broadcast_dims=[0, 1])
    T20 = fd.ops.add(T14, S1)
    T21 = fd.ops.rsqrt(T20)
    S22 = fd.define_scalar(2, dtype=DataType.Int)
    S23 = fd.define_scalar(1, dtype=DataType.Int)
    S24 = fd.define_scalar(2, dtype=DataType.Int)
    V25 = fd.define_vector([S22, S23, S24], dtype=DataType.Int)
    T26 = fd.ops.broadcast_in_dim(T19, shape=V25, broadcast_dims=[0, 1, 2])
    T27 = fd.ops.sub(T7, T26)
    S28 = fd.define_scalar(2, dtype=DataType.Int)
    S29 = fd.define_scalar(1, dtype=DataType.Int)
    S30 = fd.define_scalar(2, dtype=DataType.Int)
    V31 = fd.define_vector([S28, S29, S30], dtype=DataType.Int)
    T32 = fd.ops.broadcast_in_dim(T21, shape=V31, broadcast_dims=[0, 1, 2])
    T33 = fd.ops.mul(T27, T32)
    S34 = fd.define_scalar(2, dtype=DataType.Int)
    S35 = fd.define_scalar(2, dtype=DataType.Int)
    V36 = fd.define_vector([S34, S35], dtype=DataType.Int)
    T37 = fd.ops.reshape(T33, new_shape=V36)
    fd.add_output(T37)

with FusionDefinition() as fd:
    nvfuser_fusion_id12(fd)

inputs = [
    torch.randn((4,), dtype=torch.float32, device='cuda:0').as_strided((2, 2), (2, 1)),
    1e-05,
    1,
]
fd.execute(inputs)


Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/__init__.py", line 123, in execute
    result = self._execute(
RuntimeError: producer_id->isBroadcast() INTERNAL ASSERT FAILED at "/workspace/Fuser/csrc/root_domain_map.cpp":173, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
Exception raised from map at /workspace/Fuser/csrc/root_domain_map.cpp:173 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, char const*) + 0xd4 (0x7eff5e38c03e in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::PairwiseRootDomainMap::map(nvfuser::TensorDomain const*, nvfuser::TensorDomain const*, std::unordered_set<nvfuser::IterDomain*, std::hash<nvfuser::IterDomain*>, std::equal_to<nvfuser::IterDomain*>, std::allocator<nvfuser::IterDomain*> > const&, bool) const + 0xbdb (0x7eff5e7a70cb in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::RootDomainMap::mapProducerToConsumer(nvfuser::TensorDomain const*, nvfuser::TensorDomain const*, std::unordered_set<nvfuser::IterDomain*, std::hash<nvfuser::IterDomain*>, std::equal_to<nvfuser::IterDomain*>, std::allocator<nvfuser::IterDomain*> > const&) const + 0x10 (0x7eff5e7a3c50 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::RootDomainMap::mapProducerToConsumer(nvfuser::TensorDomain const*, nvfuser::TensorDomain const*) const + 0x68 (0x7eff5e7a8a18 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::PairwiseRootDomainMap::mapProducerToConsumer(std::unordered_set<nvfuser::IterDomain*, std::hash<nvfuser::IterDomain*>, std::equal_to<nvfuser::IterDomain*>, std::allocator<nvfuser::IterDomain*> > const*) const + 0x35 (0x7eff5e7a8af5 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #5: <unknown function> + 0x5c051d (0x7eff5e7ac51d in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #6: nvfuser::IterVisitor::traverseBetween(nvfuser::Fusion*, std::unordered_set<nvfuser::Val*, std::hash<nvfuser::Val*>, std::equal_to<nvfuser::Val*>, std::allocator<nvfuser::Val*> > const&, std::vector<nvfuser::Val*, std::allocator<nvfuser::Val*> > const&, bool, bool, bool, bool) + 0x529 (0x7eff5e5d1ec9 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #7: nvfuser::IterVisitor::traverseTo(nvfuser::Fusion*, std::vector<nvfuser::Val*, std::allocator<nvfuser::Val*> > const&, bool, bool, bool, bool) + 0x58 (0x7eff5e5d35d8 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #8: nvfuser::ExactRootDomainMap::ExactRootDomainMap(nvfuser::Fusion*) + 0xa1 (0x7eff5e7a4741 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #9: nvfuser::ExpressionEvaluator::propagateBoundValuesThroughExactMaps(nvfuser::Fusion*) + 0x2e (0x7eff5e479dae in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #10: nvfuser::DynamicTransformConcretizationInfo::DynamicTransformConcretizationInfo(nvfuser::DynamicTransformInitialInfo const*, nvfuser::ExpressionEvaluator*) + 0x95 (0x7eff5e4711d5 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #11: nvfuser::FusionExecutorCache::getKernelRuntimeFor(nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>) + 0xf4 (0x7eff5e5f6aa4 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #12: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x1ab (0x7eff5e5f78eb in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #13: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x31d (0x7eff5e8f405d in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #14: <unknown function> + 0x11319c (0x7eff5eda419c in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x158484 (0x7eff5ede9484 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: /home/mike/anaconda3/envs/3109/bin/python() [0x5006e7]
frame #17: _PyObject_MakeTpCall + 0x25b (0x4f9d9b in /home/mike/anaconda3/envs/3109/bin/python)
frame #18: /home/mike/anaconda3/envs/3109/bin/python() [0x50c6df]
frame #19: _PyEval_EvalFrameDefault + 0x13af (0x4f1dff in /home/mike/anaconda3/envs/3109/bin/python)
frame #20: /home/mike/anaconda3/envs/3109/bin/python() [0x50c546]
frame #21: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #22: _PyObject_FastCallDictTstate + 0xcd (0x4f90ed in /home/mike/anaconda3/envs/3109/bin/python)
frame #23: _PyObject_Call_Prepend + 0x66 (0x50a946 in /home/mike/anaconda3/envs/3109/bin/python)
frame #24: /home/mike/anaconda3/envs/3109/bin/python() [0x5d4b23]
frame #25: _PyObject_MakeTpCall + 0x25b (0x4f9d9b in /home/mike/anaconda3/envs/3109/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x4deb (0x4f583b in /home/mike/anaconda3/envs/3109/bin/python)
frame #27: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #29: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #31: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #32: _PyEval_EvalFrameDefault + 0x13af (0x4f1dff in /home/mike/anaconda3/envs/3109/bin/python)
frame #33: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #35: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #37: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #38: _PyEval_EvalFrameDefault + 0x31f (0x4f0d6f in /home/mike/anaconda3/envs/3109/bin/python)
frame #39: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #40: _PyEval_EvalFrameDefault + 0x31f (0x4f0d6f in /home/mike/anaconda3/envs/3109/bin/python)
frame #41: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #42: _PyEval_EvalFrameDefault + 0x4b2b (0x4f557b in /home/mike/anaconda3/envs/3109/bin/python)
frame #43: /home/mike/anaconda3/envs/3109/bin/python() [0x598dc2]
frame #44: PyEval_EvalCode + 0x87 (0x598d07 in /home/mike/anaconda3/envs/3109/bin/python)
frame #45: /home/mike/anaconda3/envs/3109/bin/python() [0x5cb4b7]
frame #46: /home/mike/anaconda3/envs/3109/bin/python() [0x5c62f0]
frame #47: /home/mike/anaconda3/envs/3109/bin/python() [0x45be54]
frame #48: _PyRun_SimpleFileObject + 0x19f (0x5c080f in /home/mike/anaconda3/envs/3109/bin/python)
frame #49: _PyRun_AnyFileObject + 0x43 (0x5c0613 in /home/mike/anaconda3/envs/3109/bin/python)
frame #50: Py_RunMain + 0x38d (0x5bd42d in /home/mike/anaconda3/envs/3109/bin/python)
frame #51: Py_BytesMain + 0x39 (0x58c339 in /home/mike/anaconda3/envs/3109/bin/python)
frame #52: <unknown function> + 0x29d90 (0x7f00af5f0d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #53: __libc_start_main + 0x80 (0x7f00af5f0e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #54: /home/mike/anaconda3/envs/3109/bin/python() [0x58c1ee]

args=(<function _create_callable.<locals>._fn at 0x7eff51cf1d80>, <function group_norm at 0x7eff789409d0>, [SampleInput args=(tensor([[ 0.1661, -0.5301],
        [-0.4739, -0.5746]], device='cuda:0'), 1, None, None) kwargs={}], <function test_core_vs_torch_consistency.<locals>.<lambda> at 0x7f00aefb3d90>), kwargs={}
Traceback (most recent call last):
  File "/home/mike/git/lightning-thunder/thunder/tests/framework.py", line 429, in run_snippet
    snippet(*args, **kwargs)
  File "/home/mike/git/lightning-thunder/thunder/tests/test_ops.py", line 36, in snippet_torch_consistency
    thunder_result = op(*sample.args, **sample.kwargs)
  File "/home/mike/git/lightning-thunder/thunder/common.py", line 749, in _fn
    result, c, extraces = _execute_trace(
  File "/home/mike/git/lightning-thunder/thunder/common.py", line 616, in _execute_trace
    result: Any = c(*args, **kwargs)
  File "/home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "LC.gen_12", line 9, in group_norm
    [t13] = nvFusion0(a, eps, num_groups)
  File "/home/mike/git/lightning-thunder/thunder/executors/nvfuserex_impl.py", line 352, in __call__
    return fd.execute(args, **kwargs)
  File "/home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/__init__.py", line 123, in execute
    result = self._execute(
RuntimeError: producer_id->isBroadcast() INTERNAL ASSERT FAILED at "/workspace/Fuser/csrc/root_domain_map.cpp":173, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
Exception raised from map at /workspace/Fuser/csrc/root_domain_map.cpp:173 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, char const*) + 0xd4 (0x7eff5e38c03e in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::PairwiseRootDomainMap::map(nvfuser::TensorDomain const*, nvfuser::TensorDomain const*, std::unordered_set<nvfuser::IterDomain*, std::hash<nvfuser::IterDomain*>, std::equal_to<nvfuser::IterDomain*>, std::allocator<nvfuser::IterDomain*> > const&, bool) const + 0xbdb (0x7eff5e7a70cb in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::RootDomainMap::mapProducerToConsumer(nvfuser::TensorDomain const*, nvfuser::TensorDomain const*, std::unordered_set<nvfuser::IterDomain*, std::hash<nvfuser::IterDomain*>, std::equal_to<nvfuser::IterDomain*>, std::allocator<nvfuser::IterDomain*> > const&) const + 0x10 (0x7eff5e7a3c50 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::RootDomainMap::mapProducerToConsumer(nvfuser::TensorDomain const*, nvfuser::TensorDomain const*) const + 0x68 (0x7eff5e7a8a18 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::PairwiseRootDomainMap::mapProducerToConsumer(std::unordered_set<nvfuser::IterDomain*, std::hash<nvfuser::IterDomain*>, std::equal_to<nvfuser::IterDomain*>, std::allocator<nvfuser::IterDomain*> > const*) const + 0x35 (0x7eff5e7a8af5 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #5: <unknown function> + 0x5c051d (0x7eff5e7ac51d in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #6: nvfuser::IterVisitor::traverseBetween(nvfuser::Fusion*, std::unordered_set<nvfuser::Val*, std::hash<nvfuser::Val*>, std::equal_to<nvfuser::Val*>, std::allocator<nvfuser::Val*> > const&, std::vector<nvfuser::Val*, std::allocator<nvfuser::Val*> > const&, bool, bool, bool, bool) + 0x529 (0x7eff5e5d1ec9 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #7: nvfuser::IterVisitor::traverseTo(nvfuser::Fusion*, std::vector<nvfuser::Val*, std::allocator<nvfuser::Val*> > const&, bool, bool, bool, bool) + 0x58 (0x7eff5e5d35d8 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #8: nvfuser::ExactRootDomainMap::ExactRootDomainMap(nvfuser::Fusion*) + 0xa1 (0x7eff5e7a4741 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #9: nvfuser::ExpressionEvaluator::propagateBoundValuesThroughExactMaps(nvfuser::Fusion*) + 0x2e (0x7eff5e479dae in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #10: nvfuser::DynamicTransformConcretizationInfo::DynamicTransformConcretizationInfo(nvfuser::DynamicTransformInitialInfo const*, nvfuser::ExpressionEvaluator*) + 0x95 (0x7eff5e4711d5 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #11: nvfuser::FusionExecutorCache::getKernelRuntimeFor(nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>) + 0xf4 (0x7eff5e5f6aa4 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #12: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x1ab (0x7eff5e5f78eb in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #13: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x31d (0x7eff5e8f405d in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so)
frame #14: <unknown function> + 0x11319c (0x7eff5eda419c in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x158484 (0x7eff5ede9484 in /home/mike/anaconda3/envs/3109/lib/python3.10/site-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: /home/mike/anaconda3/envs/3109/bin/python() [0x5006e7]
frame #17: _PyObject_MakeTpCall + 0x25b (0x4f9d9b in /home/mike/anaconda3/envs/3109/bin/python)
frame #18: /home/mike/anaconda3/envs/3109/bin/python() [0x50c6df]
frame #19: _PyEval_EvalFrameDefault + 0x13af (0x4f1dff in /home/mike/anaconda3/envs/3109/bin/python)
frame #20: /home/mike/anaconda3/envs/3109/bin/python() [0x50c546]
frame #21: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #22: _PyObject_FastCallDictTstate + 0xcd (0x4f90ed in /home/mike/anaconda3/envs/3109/bin/python)
frame #23: _PyObject_Call_Prepend + 0x66 (0x50a946 in /home/mike/anaconda3/envs/3109/bin/python)
frame #24: /home/mike/anaconda3/envs/3109/bin/python() [0x5d4b23]
frame #25: _PyObject_MakeTpCall + 0x25b (0x4f9d9b in /home/mike/anaconda3/envs/3109/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x4deb (0x4f583b in /home/mike/anaconda3/envs/3109/bin/python)
frame #27: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #29: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #31: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #32: _PyEval_EvalFrameDefault + 0x13af (0x4f1dff in /home/mike/anaconda3/envs/3109/bin/python)
frame #33: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #35: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x2a53 (0x4f34a3 in /home/mike/anaconda3/envs/3109/bin/python)
frame #37: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #38: _PyEval_EvalFrameDefault + 0x31f (0x4f0d6f in /home/mike/anaconda3/envs/3109/bin/python)
frame #39: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #40: _PyEval_EvalFrameDefault + 0x31f (0x4f0d6f in /home/mike/anaconda3/envs/3109/bin/python)
frame #41: _PyFunction_Vectorcall + 0x6f (0x500b2f in /home/mike/anaconda3/envs/3109/bin/python)
frame #42: _PyEval_EvalFrameDefault + 0x4b2b (0x4f557b in /home/mike/anaconda3/envs/3109/bin/python)
frame #43: /home/mike/anaconda3/envs/3109/bin/python() [0x598dc2]
frame #44: PyEval_EvalCode + 0x87 (0x598d07 in /home/mike/anaconda3/envs/3109/bin/python)
frame #45: /home/mike/anaconda3/envs/3109/bin/python() [0x5cb4b7]
frame #46: /home/mike/anaconda3/envs/3109/bin/python() [0x5c62f0]
frame #47: /home/mike/anaconda3/envs/3109/bin/python() [0x45be54]
frame #48: _PyRun_SimpleFileObject + 0x19f (0x5c080f in /home/mike/anaconda3/envs/3109/bin/python)
frame #49: _PyRun_AnyFileObject + 0x43 (0x5c0613 in /home/mike/anaconda3/envs/3109/bin/python)
frame #50: Py_RunMain + 0x38d (0x5bd42d in /home/mike/anaconda3/envs/3109/bin/python)
frame #51: Py_BytesMain + 0x39 (0x58c339 in /home/mike/anaconda3/envs/3109/bin/python)
frame #52: <unknown function> + 0x29d90 (0x7f00af5f0d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #53: __libc_start_main + 0x80 (0x7f00af5f0e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #54: /home/mike/anaconda3/envs/3109/bin/python() [0x58c1ee]
```

**Comment by jacobhinkle** [comment]
After looking at this more closely, I believe it is the same as #1273. I confirmed that it is fixed on TOT, since #1319 .
