### ISSUE TITLE
Duplicate expression detected during segmentation. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1437]
The following reproducer failed at head (4f8b46ce140cdc7e5af08e0cc7b2dd98ffb1010c). FWIW, #1431 happened to trigger it via Thunder's GPT2 microbenchmark. 

```
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.BFloat16, is_cpu=False)
    S1 = fd.define_scalar(None, dtype=DataType.Double)
    T2 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Bool, is_cpu=False)
    T3 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    T4 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False)
    T5 = fd.define_tensor(shape=[-1, -1, 1], contiguity=[True, True, None], dtype=DataType.Float, is_cpu=False)
    T6 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    T7 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False)
    T8 = fd.ops.cast(T2, dtype=DataType.Float)
    S9 = fd.define_scalar(16, dtype=DataType.Int)
    S10 = fd.define_scalar(128, dtype=DataType.Int)
    S11 = fd.define_scalar(1, dtype=DataType.Int)
    V12 = fd.define_vector([S9, S10, S11], dtype=DataType.Int)
    T13 = fd.ops.broadcast_in_dim(T4, shape=V12, broadcast_dims=[0, 1])
    S14 = fd.define_scalar(16, dtype=DataType.Int)
    S15 = fd.define_scalar(128, dtype=DataType.Int)
    S16 = fd.define_scalar(768, dtype=DataType.Int)
    V17 = fd.define_vector([S14, S15, S16], dtype=DataType.Int)
    T18 = fd.ops.broadcast_in_dim(T13, shape=V17, broadcast_dims=[0, 1, 2])
    T19 = fd.ops.sub(T3, T18)
    S20 = fd.define_scalar(16, dtype=DataType.Int)
    S21 = fd.define_scalar(128, dtype=DataType.Int)
    S22 = fd.define_scalar(768, dtype=DataType.Int)
    V23 = fd.define_vector([S20, S21, S22], dtype=DataType.Int)
    T24 = fd.ops.broadcast_in_dim(T5, shape=V23, broadcast_dims=[0, 1, 2])
    T25 = fd.ops.mul(T19, T24)
    S26 = fd.define_scalar(16, dtype=DataType.Int)
    S27 = fd.define_scalar(128, dtype=DataType.Int)
    S28 = fd.define_scalar(768, dtype=DataType.Int)
    V29 = fd.define_vector([S26, S27, S28], dtype=DataType.Int)
    T30 = fd.ops.broadcast_in_dim(T0, shape=V29, broadcast_dims=[2])
    T31 = fd.ops.cast(T30, dtype=DataType.Float)
    S32 = fd.define_scalar(16, dtype=DataType.Int)
    S33 = fd.define_scalar(128, dtype=DataType.Int)
    S34 = fd.define_scalar(768, dtype=DataType.Int)
    V35 = fd.define_vector([S32, S33, S34], dtype=DataType.Int)
    T36 = fd.ops.reshape(T7, new_shape=V35)
    T37 = fd.ops.cast(T36, dtype=DataType.Float)
    T38 = fd.ops.sum(T37, axes=[0, 1], keepdim=False, dtype=DataType.Null)
    T39 = fd.ops.cast(T38, dtype=DataType.BFloat16)
    T40 = fd.ops.mul(T37, T31)
    T41 = fd.ops.mul(T37, T25)
    T42 = fd.ops.sum(T41, axes=[0, 1], keepdim=False, dtype=DataType.Null)
    T43 = fd.ops.cast(T42, dtype=DataType.BFloat16)
    T44 = fd.ops.mul(T40, T24)
    T45 = fd.ops.mul(T40, T19)
    T46 = fd.ops.sum(T45, axes=[2], keepdim=False, dtype=DataType.Null)
    S47 = fd.define_scalar(16, dtype=DataType.Int)
    S48 = fd.define_scalar(128, dtype=DataType.Int)
    S49 = fd.define_scalar(1, dtype=DataType.Int)
    V50 = fd.define_vector([S47, S48, S49], dtype=DataType.Int)
    T51 = fd.ops.broadcast_in_dim(T46, shape=V50, broadcast_dims=[0, 1])
    T52 = fd.ops.neg(T44)
    T53 = fd.ops.sum(T52, axes=[2], keepdim=False, dtype=DataType.Null)
    S54 = fd.define_scalar(16, dtype=DataType.Int)
    S55 = fd.define_scalar(128, dtype=DataType.Int)
    S56 = fd.define_scalar(1, dtype=DataType.Int)
    V57 = fd.define_vector([S54, S55, S56], dtype=DataType.Int)
    T58 = fd.ops.broadcast_in_dim(T53, shape=V57, broadcast_dims=[0, 1])
    S59 = fd.define_scalar(-0.500000, dtype=DataType.Double)
    T60 = fd.ops.mul(S59, T51)
    S61 = fd.define_scalar(3.00000, dtype=DataType.Double)
    T62 = fd.ops.pow(T5, S61)
    T63 = fd.ops.mul(T60, T62)
    T64 = fd.ops.sum(T58, axes=[2], keepdim=False, dtype=DataType.Null)
    T65 = fd.ops.sum(T63, axes=[2], keepdim=False, dtype=DataType.Null)
    S66 = fd.define_scalar(16, dtype=DataType.Int)
    S67 = fd.define_scalar(128, dtype=DataType.Int)
    S68 = fd.define_scalar(1, dtype=DataType.Int)
    V69 = fd.define_vector([S66, S67, S68], dtype=DataType.Int)
    T70 = fd.ops.broadcast_in_dim(T65, shape=V69, broadcast_dims=[0, 1])
    S71 = fd.define_scalar(16, dtype=DataType.Int)
    S72 = fd.define_scalar(128, dtype=DataType.Int)
    S73 = fd.define_scalar(768, dtype=DataType.Int)
    V74 = fd.define_vector([S71, S72, S73], dtype=DataType.Int)
    T75 = fd.ops.broadcast_in_dim(T70, shape=V74, broadcast_dims=[0, 1, 2])
    S76 = fd.define_scalar(16, dtype=DataType.Int)
    S77 = fd.define_scalar(128, dtype=DataType.Int)
    S78 = fd.define_scalar(1, dtype=DataType.Int)
    V79 = fd.define_vector([S76, S77, S78], dtype=DataType.Int)
    T80 = fd.ops.broadcast_in_dim(T4, shape=V79, broadcast_dims=[0, 1])
    S81 = fd.define_scalar(16, dtype=DataType.Int)
    S82 = fd.define_scalar(128, dtype=DataType.Int)
    S83 = fd.define_scalar(768, dtype=DataType.Int)
    V84 = fd.define_vector([S81, S82, S83], dtype=DataType.Int)
    T85 = fd.ops.broadcast_in_dim(T80, shape=V84, broadcast_dims=[0, 1, 2])
    S86 = fd.define_scalar(2.00000, dtype=DataType.Double)
    T87 = fd.ops.mul(S86, T75)
    T88 = fd.ops.sub(T3, T85)
    T89 = fd.ops.mul(T87, T88)
    S90 = fd.define_scalar(768.000, dtype=DataType.Double)
    S91 = fd.ops.reciprocal(S90)
    T92 = fd.ops.mul(T89, S91)
    S93 = fd.define_scalar(16, dtype=DataType.Int)
    S94 = fd.define_scalar(128, dtype=DataType.Int)
    S95 = fd.define_scalar(1, dtype=DataType.Int)
    V96 = fd.define_vector([S93, S94, S95], dtype=DataType.Int)
    T97 = fd.ops.broadcast_in_dim(T64, shape=V96, broadcast_dims=[0, 1])
    S98 = fd.define_scalar(16, dtype=DataType.Int)
    S99 = fd.define_scalar(128, dtype=DataType.Int)
    S100 = fd.define_scalar(768, dtype=DataType.Int)
    V101 = fd.define_vector([S98, S99, S100], dtype=DataType.Int)
    T102 = fd.ops.broadcast_in_dim(T97, shape=V101, broadcast_dims=[0, 1, 2])
    S103 = fd.define_scalar(0.00130208, dtype=DataType.Double)
    T104 = fd.ops.mul(S103, T102)
    T105 = fd.ops.add(T92, T104)
    T106 = fd.ops.add(T44, T105)
    T107 = fd.ops.add(T6, T106)
    T108 = fd.ops.mul(T107, S1)
    T109 = fd.ops.mul(T108, T8)
    T110 = fd.ops.cast(T109, dtype=DataType.BFloat16)
    T111 = fd.ops.sum(T109, axes=[0], keepdim=False, dtype=DataType.Null)
    T112 = fd.ops.cast(T111, dtype=DataType.BFloat16)
    fd.add_output(T39)
    fd.add_output(T43)
    fd.add_output(T110)
    fd.add_output(T112)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.randn((768,), dtype=torch.bfloat16, device='cuda:0').as_strided((768,), (1,)),
    1.1111111111111112,
    torch.randint(0, 2, (1572864,), dtype=torch.bool, device='cuda:0').as_strided((16, 128, 768), (98304, 768, 1)),
    torch.randn((1572864,), dtype=torch.float32, device='cuda:0').as_strided((16, 128, 768), (98304, 768, 1)),
    torch.randn((2048,), dtype=torch.float32, device='cuda:0').as_strided((16, 128), (128, 1)),
    torch.randn((2048,), dtype=torch.float32, device='cuda:0').as_strided((16, 128, 1), (128, 1, 1)),
    torch.randn((1572864,), dtype=torch.float32, device='cuda:0').as_strided((16, 128, 768), (98304, 768, 1)),
    torch.randn((1572864,), dtype=torch.bfloat16, device='cuda:0').as_strided((2048, 768), (768, 1)),
]
fd.execute(inputs)
```

```
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 123, in execute
    result = self._execute(
RuntimeError: exprs.insert(expr).second INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp":3902, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Duplicate expression detected: T7_g[ iS17{i3}, iS18{i4}, iS19{i5} ]
   = (float)(T1_g[ iS1{i3}, iS2{i4}, iS3{i5} ]);

Exception raised from validateDisjoint at /opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp:3902 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7f (0x7f4c663ce272 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x5d (0x7f4c663ce4b3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::SegmentedFusion::validateDisjoint() const + 0x1e1 (0x7f4c66a44ef5 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::SegmentedFusion::validate(bool) const + 0x33 (0x7f4c66a45003 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::SegmentedFusion::validateIfDebug(bool) const + 0x27 (0x7f4c66a4502d in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #5: nvfuser::SegmentCandidateFinder::findSegments() + 0x53d (0x7f4c66a422e9 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #6: nvfuser::SegmentCandidateFinder::SegmentCandidateFinder(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SegmentCandidateFinderOptions) + 0x220 (0x7f4c66a4144e in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #7: nvfuser::SegmentCandidateFinder::segment(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SegmentCandidateFinderOptions) + 0xd7 (0x7f4c664adb4f in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #8: nvfuser::SegmentCandidateFinder::segment(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SchedulerRuntimeInfo&) + 0x143 (0x7f4c66a3a6cd in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #9: nvfuser::FusionKernelRuntime::FusionKernelRuntime(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>, long, long, long) + 0x425 (0x7f4c6662d363 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #10: std::_MakeUniq<nvfuser::FusionKernelRuntime>::__single_object std::make_unique<nvfuser::FusionKernelRuntime, std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>&, long&, long&, unsigned long>(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >&&, nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>&, long&, long&, unsigned long&&) + 0xed (0x7f4c6663d548 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #11: nvfuser::FusionExecutorCache::getKernelRuntimeFor(nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>) + 0x7c6 (0x7f4c6662bb74 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #12: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x46b (0x7f4c66629eef in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #13: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x434 (0x7f4c66b8b7ea in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #14: <unknown function> + 0x25a973 (0x7f4c676c2973 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x35ed93 (0x7f4c677c6d93 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x351f55 (0x7f4c677b9f55 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #17: <unknown function> + 0x3021a8 (0x7f4c6776a1a8 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #18: <unknown function> + 0x30227a (0x7f4c6776a27a in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #19: <unknown function> + 0x388f1a (0x7f4c677f0f1a in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #35: <unknown function> + 0x29d90 (0x7f4d8424dd90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #36: __libc_start_main + 0x80 (0x7f4d8424de40 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/repro.py", line 136, in <module>
    fd.execute(inputs)
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 123, in execute
    result = self._execute(
RuntimeError: exprs.insert(expr).second INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp":3902, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Duplicate expression detected: T7_g[ iS17{i3}, iS18{i4}, iS19{i5} ]
   = (float)(T1_g[ iS1{i3}, iS2{i4}, iS3{i5} ]);

Exception raised from validateDisjoint at /opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp:3902 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7f (0x7f4c663ce272 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x5d (0x7f4c663ce4b3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::SegmentedFusion::validateDisjoint() const + 0x1e1 (0x7f4c66a44ef5 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::SegmentedFusion::validate(bool) const + 0x33 (0x7f4c66a45003 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::SegmentedFusion::validateIfDebug(bool) const + 0x27 (0x7f4c66a4502d in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #5: nvfuser::SegmentCandidateFinder::findSegments() + 0x53d (0x7f4c66a422e9 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #6: nvfuser::SegmentCandidateFinder::SegmentCandidateFinder(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SegmentCandidateFinderOptions) + 0x220 (0x7f4c66a4144e in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #7: nvfuser::SegmentCandidateFinder::segment(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SegmentCandidateFinderOptions) + 0xd7 (0x7f4c664adb4f in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #8: nvfuser::SegmentCandidateFinder::segment(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SchedulerRuntimeInfo&) + 0x143 (0x7f4c66a3a6cd in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #9: nvfuser::FusionKernelRuntime::FusionKernelRuntime(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>, long, long, long) + 0x425 (0x7f4c6662d363 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #10: std::_MakeUniq<nvfuser::FusionKernelRuntime>::__single_object std::make_unique<nvfuser::FusionKernelRuntime, std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>&, long&, long&, unsigned long>(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >&&, nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>&, long&, long&, unsigned long&&) + 0xed (0x7f4c6663d548 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #11: nvfuser::FusionExecutorCache::getKernelRuntimeFor(nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>) + 0x7c6 (0x7f4c6662bb74 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #12: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x46b (0x7f4c66629eef in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #13: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x434 (0x7f4c66b8b7ea in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #14: <unknown function> + 0x25a973 (0x7f4c676c2973 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x35ed93 (0x7f4c677c6d93 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x351f55 (0x7f4c677b9f55 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #17: <unknown function> + 0x3021a8 (0x7f4c6776a1a8 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #18: <unknown function> + 0x30227a (0x7f4c6776a27a in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #19: <unknown function> + 0x388f1a (0x7f4c677f0f1a in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #35: <unknown function> + 0x29d90 (0x7f4d8424dd90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #36: __libc_start_main + 0x80 (0x7f4d8424de40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by wujingyue** [comment]
`git bisect` points to dcf97b793fd520163d41a54daa45ad78e0941609. I'll try reverting that...
