### ISSUE TITLE
!detect_exception_in_thread_pool.load() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/kernel_cache.cpp":1307

### ISSUE THREAD

**Issue by crcrpar** [NVIDIA/Fuser#1697]
### environment
- nvfuser: 0.1.5+gitd8589a4
- gpu: H100 80GB HBM3
- PyTorch: 2.3.0a0+git42062e2
- CUDA: 12.3

### error
```
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 137, in execute
    result = self._execute(
RuntimeError: !detect_exception_in_thread_pool.load() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/kernel_cache.cpp":1307, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Detected exception while compiling fusion segments in parallel.
Use NVFUSER_DISABLE=parallel_compile to print exception message.
Exception raised from compileFusionParallel at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:1307 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f1a32f4ce09 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7f1a330a18a3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x118f (0x7f1a332107df in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0xa33 (0x7f1a3321b3c3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x16c (0x7f1a33535cec in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #5: <unknown function> + 0xf151e (0x7f1a3388751e in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x177458 (0x7f1a3390d458 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #22: <unknown function> + 0x29d90 (0x7f1c5d63ad90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #23: __libc_start_main + 0x80 (0x7f1c5d63ae40 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "/opt/pytorch//nvfuser_failure_in_Llama-2-7b-hf.py", line 102, in <module>
    fd.execute(inputs)
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 137, in execute
    result = self._execute(
RuntimeError: !detect_exception_in_thread_pool.load() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/kernel_cache.cpp":1307, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Detected exception while compiling fusion segments in parallel.
Use NVFUSER_DISABLE=parallel_compile to print exception message.
Exception raised from compileFusionParallel at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:1307 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f1a32f4ce09 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7f1a330a18a3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x118f (0x7f1a332107df in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0xa33 (0x7f1a3321b3c3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x16c (0x7f1a33535cec in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #5: <unknown function> + 0xf151e (0x7f1a3388751e in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x177458 (0x7f1a3390d458 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #22: <unknown function> + 0x29d90 (0x7f1c5d63ad90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #23: __libc_start_main + 0x80 (0x7f1c5d63ae40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

### script to reproduce
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id15(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, -1, -1], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T1 = fd.define_tensor(shape=[1, -1, -1], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T2 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[0])
    T3 = fd.ops.cast(T0, dtype=DataType.Float)
    T4 = fd.ops.cast(T1, dtype=DataType.Float)
    T5 = fd.ops.add(T4, T3)
    T6 = fd.ops.cast(T5, dtype=DataType.BFloat16)
    T7 = fd.ops.mul(T5, T5)
    T8 = fd.ops.sum(T7, axes=[2], keepdim=False, dtype=DataType.Null)
    S9 = fd.define_scalar(1, dtype=DataType.Int)
    S10 = fd.define_scalar(4096, dtype=DataType.Int)
    S11 = fd.define_scalar(1, dtype=DataType.Int)
    V12 = fd.define_vector([S9, S10, S11], dtype=DataType.Int)
    T13 = fd.ops.broadcast_in_dim(T8, shape=V12, broadcast_dims=[0, 1])
    S14 = fd.define_scalar(4096.00, dtype=DataType.Double)
    S15 = fd.ops.reciprocal(S14)
    T16 = fd.ops.mul(T13, S15)
    S17 = fd.define_scalar(1.00000e-05, dtype=DataType.Double)
    T18 = fd.ops.add(T16, S17)
    T19 = fd.ops.rsqrt(T18)
    T20 = fd.ops.cast(T19, dtype=DataType.BFloat16)
    S21 = fd.define_scalar(1, dtype=DataType.Int)
    S22 = fd.define_scalar(4096, dtype=DataType.Int)
    S23 = fd.define_scalar(4096, dtype=DataType.Int)
    V24 = fd.define_vector([S21, S22, S23], dtype=DataType.Int)
    T25 = fd.ops.broadcast_in_dim(T20, shape=V24, broadcast_dims=[0, 1, 2])
    T26 = fd.ops.cast(T25, dtype=DataType.Float)
    T27 = fd.ops.mul(T5, T26)
    S28 = fd.define_scalar(8, dtype=DataType.Int)
    S29 = fd.define_scalar(25297920, dtype=DataType.Int)
    V30 = fd.define_vector([S28, S29], dtype=DataType.Int)
    T31 = fd.ops.reshape(T2, new_shape=V30)
    T32 = fd.ops.slice(T31, start_indices=[0, 0], end_indices=[8, 512], strides=[1, 1])
    S33 = fd.define_scalar(4096, dtype=DataType.Int)
    V34 = fd.define_vector([S33], dtype=DataType.Int)
    T35 = fd.ops.reshape(T32, new_shape=V34)
    T36 = fd.ops.slice(T31, start_indices=[0, 512], end_indices=[8, 6291968], strides=[1, 1])
    S37 = fd.define_scalar(12288, dtype=DataType.Int)
    S38 = fd.define_scalar(4096, dtype=DataType.Int)
    V39 = fd.define_vector([S37, S38], dtype=DataType.Int)
    T40 = fd.ops.reshape(T36, new_shape=V39)
    T41 = fd.ops.slice(T31, start_indices=[0, 6291968], end_indices=[8, 8389120], strides=[1, 1])
    S42 = fd.define_scalar(4096, dtype=DataType.Int)
    S43 = fd.define_scalar(4096, dtype=DataType.Int)
    V44 = fd.define_vector([S42, S43], dtype=DataType.Int)
    T45 = fd.ops.reshape(T41, new_shape=V44)
    T46 = fd.ops.slice(T31, start_indices=[0, 8389120], end_indices=[8, 8389632], strides=[1, 1])
    S47 = fd.define_scalar(4096, dtype=DataType.Int)
    V48 = fd.define_vector([S47], dtype=DataType.Int)
    T49 = fd.ops.reshape(T46, new_shape=V48)
    T50 = fd.ops.slice(T31, start_indices=[0, 8389632], end_indices=[8, 14025728], strides=[1, 1])
    S51 = fd.define_scalar(11008, dtype=DataType.Int)
    S52 = fd.define_scalar(4096, dtype=DataType.Int)
    V53 = fd.define_vector([S51, S52], dtype=DataType.Int)
    T54 = fd.ops.reshape(T50, new_shape=V53)
    T55 = fd.ops.slice(T31, start_indices=[0, 14025728], end_indices=[8, 19661824], strides=[1, 1])
    S56 = fd.define_scalar(11008, dtype=DataType.Int)
    S57 = fd.define_scalar(4096, dtype=DataType.Int)
    V58 = fd.define_vector([S56, S57], dtype=DataType.Int)
    T59 = fd.ops.reshape(T55, new_shape=V58)
    T60 = fd.ops.slice(T31, start_indices=[0, 19661824], end_indices=[8, 25297920], strides=[1, 1])
    S61 = fd.define_scalar(4096, dtype=DataType.Int)
    S62 = fd.define_scalar(11008, dtype=DataType.Int)
    V63 = fd.define_vector([S61, S62], dtype=DataType.Int)
    T64 = fd.ops.reshape(T60, new_shape=V63)
    S65 = fd.define_scalar(1, dtype=DataType.Int)
    S66 = fd.define_scalar(4096, dtype=DataType.Int)
    S67 = fd.define_scalar(4096, dtype=DataType.Int)
    V68 = fd.define_vector([S65, S66, S67], dtype=DataType.Int)
    T69 = fd.ops.broadcast_in_dim(T35, shape=V68, broadcast_dims=[2])
    T70 = fd.ops.cast(T69, dtype=DataType.Float)
    T71 = fd.ops.mul(T70, T27)
    T72 = fd.ops.cast(T71, dtype=DataType.BFloat16)
    S73 = fd.define_scalar(1, dtype=DataType.Int)
    S74 = fd.define_scalar(4096, dtype=DataType.Int)
    S75 = fd.define_scalar(4096, dtype=DataType.Int)
    V76 = fd.define_vector([S73, S74, S75], dtype=DataType.Int)
    T77 = fd.ops.broadcast_in_dim(T49, shape=V76, broadcast_dims=[2])
    T78 = fd.ops.cast(T77, dtype=DataType.Float)
    fd.add_output(T78)
    fd.add_output(T6)
    fd.add_output(T19)
    fd.add_output(T40)
    fd.add_output(T45)
    fd.add_output(T54)
    fd.add_output(T59)
    fd.add_output(T64)
    fd.add_output(T72)

with FusionDefinition() as fd:
    nvfuser_fusion_id15(fd)

inputs = [
    torch.randn((16777216,), dtype=torch.bfloat16, device='cuda:0').as_strided((1, 4096, 4096), (16777216, 4096, 1)),
    torch.randn((16777216,), dtype=torch.bfloat16, device='cuda:0').as_strided((1, 4096, 4096), (16777216, 4096, 1)),
    torch.randn((202383360,), dtype=torch.bfloat16, device='cuda:0').as_strided((202383360,), (1,)),
]
fd.execute(inputs)
```

**Comment by naoyam** [comment]
Could you try `NVFUSER_DISABLE=parallel_compile`?

**Comment by jacobhinkle** [comment]
Looks like the error is
> RuntimeError: bdimx() * bdimy() * bdimz() > 0 && bdimx() * bdimy() * bdimz() <= (int64_t)at::cuda::getCurrentDeviceProperti
es() ->maxThreadsPerMultiProcessor INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor_params.cpp":30, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Selected invalid number of threads for cuda: 6324480 

This large segment has an input of size `[i832, i833] = [8, 25297920]`, and the scheduled fusion has this in it:
```
T214_l[ ithreadIdx.x1003{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}_p, iS1000{4}, iUS1002{1}, iS999{8
} ] ca_pos( 4 )                                              
   = Set( T42_g[ iS1009{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}, iS1006{4}, iS1008{1}, iS1005{8} ]
, cache_op=Streaming )
```
25297920/4 = 6324480. I think this is the inner persistent scheduler. cc @liqiangxl

**Comment by liqiangxl** [comment]
> Looks like the error is
> 
> > RuntimeError: bdimx() * bdimy() * bdimz() > 0 && bdimx() * bdimy() * bdimz() <= (int64_t)at::cuda::getCurrentDeviceProperti
> > es() ->maxThreadsPerMultiProcessor INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor_params.cpp":30, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Selected invalid number of threads for cuda: 6324480
> 
> This large segment has an input of size `[i832, i833] = [8, 25297920]`, and the scheduled fusion has this in it:
> 
> ```
> T214_l[ ithreadIdx.x1003{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}_p, iS1000{4}, iUS1002{1}, iS999{8
> } ] ca_pos( 4 )                                              
>    = Set( T42_g[ iS1009{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}, iS1006{4}, iS1008{1}, iS1005{8} ]
> , cache_op=Streaming )
> ```
> 
> 25297920/4 = 6324480. I think this is the inner persistent scheduler. cc @liqiangxl

Thanks for the info. Looks like the error is caused by the slice op fused with reduction. I'll take a look.

**Comment by liqiangxl** [comment]
**Reason:** The err is becuase we are caching the slice input tv. `T42_g` is the original slice input, cached as `T214_l`, then changed to smem `T219_s`, finally do the slice.
```
T214_l[ iS1018{4}, iUS1020{1}, ithreadIdx.x1021{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}_p, iS1017{8} ] ca_pos( 4 )
   = Set( T42_g[ iS1024{4}, iS1026{1}, iS1027{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}, iS1023{8} ], cache_op=Streaming )
T219_s[ iS1012{4}, iUS1014{1}, ithreadIdx.x1015{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}_p, iS1011{8} ] produce_pos( 4 )
   = Set( T214_l[ iS1018{4}, iUS1020{1}, ithreadIdx.x1021{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}_p, iS1017{8} ] ca_pos( 4 ), cache_op=Streaming )
T20_l[ iS1006{4}, iUS1008{1}, ithreadIdx.x1009{( ceilDiv(( ceilDiv(( ceilDiv(( 8 * 512 ), 8) ), 4) ), 1) )}_p, iS1005{8} ] ca_pos( 4 )
   = slice( T219_s[ iS1012{4}, iUS1014{1}, ithreadIdx.x1015{( ceilDiv(( ceilDiv(( ceilDiv(( i832 * i833 ), 8) ), 4) ), 1) )}_p, iS1011{8} ] produce_pos( 4 ), { {0, 8, 1} {0, 512, 1} } )

```

**Fix:** don't cache if the input tv is used by slice.
