### ISSUE TITLE
Standalone install should work with (editable) install PyTorch with `BUILD_NVFUSER=0`

### ISSUE THREAD

**Issue by crcrpar** [NVIDIA/Fuser#200]
## Condition
- PyTorch: 2.1.0a0+gitda57d59 (as of https://github.com/pytorch/pytorch/commit/233cc34d3b8a1b92eeeea78661463f8ec660fbcd).
    - Command: `BUILD_NVFUSER=0 python setup.py develop`
- Fuser: b644b338e6e10e2a353cee7f433e50913c295db5

## Repro steps
```console
$ cd /path/to/nvidia/fuser
$ pip install -v -e .
Using pip 22.3.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
Obtaining file:///opt/pytorch/nvfuser
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  ==== importing nvfuser failed ====
               try run `patch-nvfuser` if https://github.com/NVIDIA/Fuser is installed via pip package

...

  running egg_info
  creating /tmp/pip-pip-egg-info-8qqasdji/nvfuser.egg-info
  writing /tmp/pip-pip-egg-info-8qqasdji/nvfuser.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-8qqasdji/nvfuser.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-pip-egg-info-8qqasdji/nvfuser.egg-info/entry_points.txt
  writing top-level names to /tmp/pip-pip-egg-info-8qqasdji/nvfuser.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-8qqasdji/nvfuser.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-8qqasdji/nvfuser.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-8qqasdji/nvfuser.egg-info/SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/opt/pytorch/nvfuser/setup.py", line 340, in <module>
      main()
    File "/opt/pytorch/nvfuser/setup.py", line 336, in main
      subprocess.check_call(["patch-nvfuser"])
    File "/usr/local/lib/python3.10/subprocess.py", line 364, in check_call
      retcode = call(*popenargs, **kwargs)
    File "/usr/local/lib/python3.10/subprocess.py", line 345, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'patch-nvfuser'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

...
```

The entire log is: https://gist.github.com/crcrpar/35d308ad57e6bbb789d34a7463d48688.

**Comment by jjsjann123** [comment]
Looks like it's just complaining about `patch-nvfuser`, which is just the missing entry point....
I think we can update the setup script to run the python script directly, instead of relying on a installed `patch-nvfuser`.

**Comment by crcrpar** [comment]
`python setup.py develop` seems to work, which is great.

What I don't understand by looking at the log is that why the raise in the block below is not bothering. https://github.com/NVIDIA/Fuser/blob/b644b338e6e10e2a353cee7f433e50913c295db5/nvfuser/__init__.py#L15-L26
