### ISSUE TITLE
`RuntimeError: Stride mismatch with contiguity info.`

### ISSUE THREAD

**Issue by crcrpar** [NVIDIA/Fuser#2354]
env
- H100
- `torch.__version__ = '2.4.0a0+gitfb696ef'`
- cuda = `12.5`
- `nvfuser.version() = '0.2.6+gita286c31'`

repro

```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T1 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False, stride_order=[0])
    T2 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T3 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[2, 1, 0])
    T4 = fd.ops.linear(T3, T2, T1)
    S5 = fd.define_scalar(1.41421, dtype=DataType.Double)
    S6 = fd.ops.reciprocal(S5)
    T7 = fd.ops.mul(T4, S6)
    T8 = fd.ops.erf(T7)
    S9 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T10 = fd.ops.mul(S9, T8)
    S11 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T12 = fd.ops.add(S11, T10)
    T13 = fd.ops.mul(T4, T12)
    T14 = fd.ops.linear(T13, T0)
    fd.add_output(T4)
    fd.add_output(T13)
    fd.add_output(T14)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.randn((1179648,), dtype=torch.float32, device='cuda:0').as_strided((768, 1536), (1536, 1)),
    torch.randn((1536,), dtype=torch.float32, device='cuda:0').as_strided((1536,), (1,)),
    torch.randn((1179648,), dtype=torch.float32, device='cuda:0').as_strided((1536, 768), (768, 1)),
    torch.randn((6291456,), dtype=torch.float32, device='cuda:0').as_strided((2048, 4, 768), (3072, 768, 1)),
]
fd.execute(inputs)
```

error

```log
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 139, in execute
    result = self._execute(
RuntimeError: Stride mismatch with contiguity info.  allocation domain: iS116{( (( (( getMetaData(T4) )).logical_size ))[2] )}, iS117{( (( (( getMetaData(T4) )).logical_size ))[0] )}, iS118{( (( (( getMetaData(T4) )).logical_size ))[1] )} dim: 2 expected stride: 1 actual stride: 1536
Exception raised from validateAllocationSizesAndStrides at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:237 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7fb5794521e1 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: <unknown function> + 0x7b9490 (0x7fb579ae7490 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x7b9e78 (0x7fb579ae7e78 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: nvfuser::Expr::evaluate(nvfuser::ExpressionEvaluator const&, std::unordered_map<nvfuser::Val const*, dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>, std::hash<nvfuser::Val const*>, std::equal_to<nvfuser::Val const*>, std::allocator<std::pair<nvfuser::Val const* const, dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool> > > >&) const + 0x11b (0x7fb5798a54eb in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x48daa7 (0x7fb5797bbaa7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x42a8fa (0x7fb5797588fa in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x42b1e8 (0x7fb5797591e8 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x45c8d0 (0x7fb57978a8d0 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #8: nvfuser::FusionExecutor::runFusion(nvfuser::KernelArgumentHolder&, nvfuser::LaunchParams const&, nvfuser::CompileParams, std::vector<at::Tensor, std::allocator<at::Tensor> >) + 0x6c7 (0x7fb57978bee7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x64274e (0x7fb57997074e in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x648011 (0x7fb579976011 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #11: nvfuser::FusionKernelRuntime::runWithInputs(nvfuser::KernelArgumentHolder&) + 0xa9 (0x7fb579976869 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #12: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x3fe (0x7fb5799817be in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #13: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x3c8 (0x7fb579b6eb98 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x19be25 (0x7fb5794c9e25 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x210962 (0x7fb57953e962 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x29ff80 (0x7fb5795cdf80 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #32: <unknown function> + 0x29d90 (0x7fb7b9838d90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #33: __libc_start_main + 0x80 (0x7fb7b9838e40 in /usr/lib/x86_64-linux-gnu/libc.so.6)

torch.__version__ = '2.4.0a0+gitfb696ef', torch.version.cuda = '12.5'
nvfuser.version() = '0.2.6+gita286c31'
Traceback (most recent call last):
  File "/opt/pytorch/lightning-thunder/nvfuser_failure_repro.py", line 37, in <module>
    fd.execute(inputs)
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 139, in execute
    result = self._execute(
RuntimeError: Stride mismatch with contiguity info.  allocation domain: iS116{( (( (( getMetaData(T4) )).logical_size ))[2] )}, iS117{( (( (( getMetaData(T4) )).logical_size ))[0] )}, iS118{( (( (( getMetaData(T4) )).logical_size ))[1] )} dim: 2 expected stride: 1 actual stride: 1536
Exception raised from validateAllocationSizesAndStrides at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:237 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7fb5794521e1 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: <unknown function> + 0x7b9490 (0x7fb579ae7490 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x7b9e78 (0x7fb579ae7e78 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: nvfuser::Expr::evaluate(nvfuser::ExpressionEvaluator const&, std::unordered_map<nvfuser::Val const*, dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>, std::hash<nvfuser::Val const*>, std::equal_to<nvfuser::Val const*>, std::allocator<std::pair<nvfuser::Val const* const, dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool> > > >&) const + 0x11b (0x7fb5798a54eb in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x48daa7 (0x7fb5797bbaa7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x42a8fa (0x7fb5797588fa in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x42b1e8 (0x7fb5797591e8 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x45c8d0 (0x7fb57978a8d0 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #8: nvfuser::FusionExecutor::runFusion(nvfuser::KernelArgumentHolder&, nvfuser::LaunchParams const&, nvfuser::CompileParams, std::vector<at::Tensor, std::allocator<at::Tensor> >) + 0x6c7 (0x7fb57978bee7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x64274e (0x7fb57997074e in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x648011 (0x7fb579976011 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #11: nvfuser::FusionKernelRuntime::runWithInputs(nvfuser::KernelArgumentHolder&) + 0xa9 (0x7fb579976869 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #12: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x3fe (0x7fb5799817be in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #13: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x3c8 (0x7fb579b6eb98 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x19be25 (0x7fb5794c9e25 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x210962 (0x7fb57953e962 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x29ff80 (0x7fb5795cdf80 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #32: <unknown function> + 0x29d90 (0x7fb7b9838d90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #33: __libc_start_main + 0x80 (0x7fb7b9838e40 in /usr/lib/x86_64-linux-gnu/libc.so.6)

```

**Comment by jacobhinkle** [comment]
cc @Priya2698 and @jjsjann123. I think this is an issue with `LinearOp` and allocation domain propagation. This segments into three segments: ExprEval, Pointwise, ExprEval. The first ExprEval is computing a `LinearOp` whose stride order doesn't match waht the pointwise segment is expecting.

**Comment by jjsjann123** [comment]
So this feels like we should either propagate the allocation domain prior to segmentation. I think this is as part of an optimization? not just for matmul, but generally a scheduler making a decision on the memory format of an intermediate tensor needs to be propagated to its neighbors, but that might not be within the scope of this issue.

At the same time, we should also ensure that `ExprEval` produce output as required by the original fusion definition.

**Comment by jjsjann123** [comment]
I'm volunteering @Priya2698 for this issue :stuck_out_tongue_winking_eye:

**Comment by jacobhinkle** [comment]
> we should modify the allocation order inference to set the order for linear/matmul differently

Yeah it seems like we need to add some `handle` specializations in `AllocationOrderInferencer`.

> I am not sure how this should be generalized to handle cases where the allocation domain is being propagated from some other expressions down to linear.

We should probably try and determine the rules that `at::matmul` and `at::linear` use and mimic those in `AllocationOrderInferencer`. This actually might be super simple: at least for `matmul` I haven't found a combination that gives a non-trivial stride order. Try the following script:
```python
import numpy as np
import torch

import itertools


def make_tensor_with_stride_order(
    shape: tuple[int], stride_order: tuple[int], **kwargs
):
    strides = [-1 for _ in range(len(shape))]
    stride = 1
    for dim in stride_order:
        strides[dim] = stride
        stride *= shape[dim]
    out = torch.randn(shape, **kwargs)
    out = out.as_strided(shape, strides)
    return out


def run_all_stride_orders(
    Ashape: tuple[int], Bshape: tuple[int], dtype: torch.dtype = torch.half
):
    for Aorder, Border in itertools.product(
        itertools.permutations(range(len(Ashape))),
        itertools.permutations(range(len(Bshape))),
    ):
        Aperm = make_tensor_with_stride_order(
            Ashape, Aorder, device="cuda", dtype=dtype
        )
        Bperm = make_tensor_with_stride_order(
            Bshape, Border, device="cuda", dtype=dtype
        )

        # construct Aperm and Bperm by permuting the stride order
        D = torch.matmul(Aperm, Bperm)
        # get the permutation of the stride which is the stride order
        Dorder = tuple(np.argsort(D.stride()))
        print(
            f"stride order A={Aorder}, stride order B={Border} output strides={D.stride()} output order={Dorder}"
        )


B = 16
M = 128
N = 256
K = 64

run_all_stride_orders([K], [K])
run_all_stride_orders([K], [K, N])
run_all_stride_orders([M, K], [K])
run_all_stride_orders([M, K], [K, N])
run_all_stride_orders([B, M, K], [K, N])
run_all_stride_orders([M, K], [B, K, N])
run_all_stride_orders([B, M, K], [B, K, N])
run_all_stride_orders([B, B, M, K], [B, K, N])
```

**Comment by jjsjann123** [comment]
> For me this shows that all input combos give the default stride order to the output, so maybe the propagation should just stop whenever we get to a MatmulOp or LinearOp.

Yeah, sorry that was agreed upon in an offline discussion. allocation order inference isn't making the right decision there. I'll kick off a PR to patch that.

At the same time, nvfuser API still allows user to specify output with a stride order. So our evaluator should still support that via tensor operations (permute/contiguous/permute).
@Priya2698 is worried about noisy regression if we went ahead and patched the executor without patching allocation order inference first. So I'll patch that quickly.

**Comment by Priya2698** [comment]
Ahh, sorry, forgot to update it here. @jjsjann123 and I agreed upon the following in the offline discussion:
1. The expression evaluator will raise a warning if there is an allocation domain set. I am worried about missing cases like this which will show regressions due to unnecessary reordering.
2. The allocation domain inference will be patched to avoid reordering allocation domain for `MatmulOp/LinearOp`.
