### ISSUE TITLE
codegen RuntimeError: Multiple reductions requires an iter domain, but one wasn't found.

### ISSUE THREAD

**Issue by jjsjann123** [NVIDIA/Fuser#236]
Run into this issue with cross_entropy example.

error show up as:
```
Traceback (most recent call last):
  File "/jiej/playground/lightning-thunder/../repro_crossEntropyLoss.py", line 74, in <module>
    o = fd.execute(inputs)
  File "/opt/pytorch/pytorch/nvfuser/__init__.py", line 78, in execute
    raise RuntimeError(err)
RuntimeError: !(rparams.multiple_reds_per_blk && !has_iter_axis) INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/scheduler/reduction_utils.cpp":56, please report a bug to PyTorch. Multiple reductions requires an iter domain, but one wasn't found
```

python repro vvv
```
import torch
from nvfuser import FusionDefinition, DataType

dtype = torch.float64

inputs = [
    torch.randn(5, dtype=dtype, device='cuda'),
    torch.randn(5, dtype=dtype, device='cuda'),
    torch.randint(0, 5, (), device="cuda"),
]


def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Double, is_cpu=False)
    T1 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Double, is_cpu=False)
    T2 = fd.define_tensor(symbolic_sizes=[], contiguity=[], dtype=DataType.Int, is_cpu=False)
    T3 = fd.ops.reshape(T0, original_shape=[5], new_shape=[5])
    T4 = fd.ops.max(T1, axes=[0], keepdim=False, dtype=DataType.Null)
    T5 = fd.ops.broadcast_in_dim(T4, output_shape=[1], broadcast_dims=[])
    T6 = fd.ops.broadcast_in_dim(T5, output_shape=[5], broadcast_dims=[0])
    T7 = fd.ops.sub(T1, T6)
    T8 = fd.ops.exp(T7)
    T9 = fd.ops.sum(T8, axes=[0], keepdim=False, dtype=DataType.Null)
    T10 = fd.ops.broadcast_in_dim(T9, output_shape=[1], broadcast_dims=[])
    T11 = fd.ops.broadcast_in_dim(T10, output_shape=[5], broadcast_dims=[0])
    T12 = fd.ops.div(T8, T11)
    T13 = fd.ops.log(T12)
    T14 = fd.ops.neg(T13)
    T15 = fd.ops.mul(T14, T3)
    T16 = fd.ops.reshape(T2, original_shape=[], new_shape=[1])
    T17 = fd.ops.gather(T15, T16, dim=0)
    fd.add_output(T17)

f = FusionDefinition()

print("tensor 0")
print(inputs[0].shape)
print(inputs[0].stride())

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

print(fd)
for _ in range(5) :
    o = fd.execute(inputs)
```

**Comment by jjsjann123** [comment]
wait a second.. the repro isn't right....

**Comment by jjsjann123** [comment]
Requested by @naoyam with `PYTORCH_NVFUSER_DUMP=segmented_fusion`

```
Segment the fusion (Original Fusion Un-modified):
Inputs:
  T0_g[ iS0{i0} ], double
  T1_g[ iS1{i2} ], double
  T2_g[ 0 ], int64_t
Outputs:
  T18_g[ bS17{1} ], double

%kernel_math {
T3_l[ rS2{i2} ]
   = reduction( T1_g[ iS1{i2} ], op = fmax, initial value = double(-inf), allreduce = false )
T4_l[ bS3{1} ]
   = broadcast( T3_l[ rS2{i2} ] )
T5_l[ bS4{1} ]
   = Set( T4_l[ bS3{1} ] )
T6_l[ bS5{5} ] = expand( T5_l[ bS4{1} ], {5} )
T7_l[ iS6{i2} ]
   = T1_g[ iS1{i2} ]
   - T6_l[ bS5{5} ];
T8_g[ iS7{i2} ]
   = exp(T7_l[ iS6{i2} ]);
T9_g[ rS8{i2} ]
   = reduction( T8_g[ iS7{i2} ], op = add, initial value = double(0), allreduce = false )
T10_g[ bS9{1} ]
   = broadcast( T9_g[ rS8{i2} ] )
T11_g[ bS10{1} ]
   = Set( T10_g[ bS9{1} ] )
T12_l[ bS11{5} ] = expand( T11_g[ bS10{1} ], {5} )
T13_g[ iS12{i2} ]
   = T8_g[ iS7{i2} ]
   / T12_l[ bS11{5} ];
T14_g[ iS13{i2} ]
   = log(T13_g[ iS12{i2} ]);
T15_l[ iS14{i2} ]
   = -T14_g[ iS13{i2} ];
T16_g[ iS15{i2} ]
   = T15_l[ iS14{i2} ]
   * T0_g[ iS0{i0} ];
T17_g[ bS16{1} ]
   = broadcast( T2_g[ 0 ] )
T18_g[ bS17{1} ]
   = torch_gather( T16_g[ iS15{i2} ], dim = 0, T17_g[ bS16{1} ] )
}

Segmented_Fusion Dump: -- Re-written complete fusion:{
Inputs:
  T0_g[ iS0{i0} ], double
  T1_g[ iS1{i2} ], double
  T2_g[ 0 ], int64_t
Outputs:
  T18_g[ bS17{1} ], double

%kernel_math {
T3_l[ rS2{i2} ]
   = reduction( T1_g[ iS1{i2} ], op = fmax, initial value = double(-inf), allreduce = false )
T4_l[ bS3{1} ]
   = broadcast( T3_l[ rS2{i2} ] )
T5_l[ bS4{1} ]
   = Set( T4_l[ bS3{1} ] )
T6_l[ bS5{5} ] = expand( T5_l[ bS4{1} ], {5} )
T7_l[ iS6{i2} ]
   = T1_g[ iS1{i2} ]
   - T6_l[ bS5{5} ];
T8_g[ iS7{i2} ]
   = exp(T7_l[ iS6{i2} ]);
T9_g[ rS8{i2} ]
   = reduction( T8_g[ iS7{i2} ], op = add, initial value = double(0), allreduce = false )
T10_g[ bS9{1} ]
   = broadcast( T9_g[ rS8{i2} ] )
T11_g[ bS10{1} ]
   = Set( T10_g[ bS9{1} ] )
T12_l[ bS11{5} ] = expand( T11_g[ bS10{1} ], {5} )
T13_g[ iS12{i2} ]
   = T8_g[ iS7{i2} ]
   / T12_l[ bS11{5} ];
T14_g[ iS13{i2} ]
   = log(T13_g[ iS12{i2} ]);
T15_l[ iS14{i2} ]
   = -T14_g[ iS13{i2} ];
T16_g[ iS15{i2} ]
   = T15_l[ iS14{i2} ]
   * T0_g[ iS0{i0} ];
T17_g[ bS16{1} ]
   = broadcast( T2_g[ 0 ] )
T18_g[ bS17{1} ]
   = torch_gather( T16_g[ iS15{i2} ], dim = 0, T17_g[ bS16{1} ] )
}

} // {Re-written complete fusion}
Segmented_Fusion Dump: -- fusion segments:
Segmented_Fusion{
groups:
g{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13}

g{14, 15}

edges:
e{ g{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13}
 -> g{14, 15}
(T16_g[ iS15{i2} ]) }


group details:
g{(persistent)
inputs:
T0_g[ iS0{i0} ] double
T1_g[ iS1{i2} ] double
outputs:
T16_g[ iS15{i2} ] double


T3_l[ rS2{i2} ]
   = reduction( T1_g[ iS1{i2} ], op = fmax, initial value = double(-inf), allreduce = false )
(0)
T4_l[ bS3{1} ]
   = broadcast( T3_l[ rS2{i2} ] )
(1)
T5_l[ bS4{1} ]
   = Set( T4_l[ bS3{1} ] )
(2)
T6_l[ bS5{5} ] = expand( T5_l[ bS4{1} ], {5} )
(3)
T7_l[ iS6{i2} ]
   = T1_g[ iS1{i2} ]
   - T6_l[ bS5{5} ];
(4)
T8_g[ iS7{i2} ]
   = exp(T7_l[ iS6{i2} ]);
(5)
T9_g[ rS8{i2} ]
   = reduction( T8_g[ iS7{i2} ], op = add, initial value = double(0), allreduce = false )
(6)
T10_g[ bS9{1} ]
   = broadcast( T9_g[ rS8{i2} ] )
(7)
T11_g[ bS10{1} ]
   = Set( T10_g[ bS9{1} ] )
(8)
T12_l[ bS11{5} ] = expand( T11_g[ bS10{1} ], {5} )
(9)
T13_g[ iS12{i2} ]
   = T8_g[ iS7{i2} ]
   / T12_l[ bS11{5} ];
(10)
T14_g[ iS13{i2} ]
   = log(T13_g[ iS12{i2} ]);
(11)
T15_l[ iS14{i2} ]
   = -T14_g[ iS13{i2} ];
(12)
T16_g[ iS15{i2} ]
   = T15_l[ iS14{i2} ]
   * T0_g[ iS0{i0} ];
(13)
}

g{(no-op)
inputs:
T2_g[ 0 ] int64_t
T16_g[ iS15{i2} ] double
outputs:
T18_g[ bS17{1} ] double


T17_g[ bS16{1} ]
   = broadcast( T2_g[ 0 ] )
(14)
T18_g[ bS17{1} ]
   = torch_gather( T16_g[ iS15{i2} ], dim = 0, T17_g[ bS16{1} ] )
(15)
}

} //Segmented_Fusion


```

**Comment by naoyam** [comment]
Don't know what's going on but here's a small repro:

```
TEST_F(NVFuserTest, DoublePrecisionNorm_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  DataType dt = DataType::Float;

  if (getenv("DP")) {
    dt = DataType::Double;
  }

  auto tv0 = makeSymbolicTensor(1, dt);
  fusion->addInput(tv0);
  auto tv1 = makeSymbolicTensor(1, dt);
  fusion->addInput(tv1);

  auto tv2 = sum(tv1, {0});
  auto tv3 = broadcast(tv2, {true});
  auto tv4 = sub(tv1, tv3);
  auto tv5 = mul(tv4, tv0);
  fusion->addOutput(tv5);

  auto options = at::TensorOptions().dtype(data_type_to_aten(dt)).device(at::kCUDA, 0);
  at::manual_seed(0);
  at::Tensor t0 = at::randn({5}, options);
  at::Tensor t1 = at::randn({5}, options);
  std::vector<c10::IValue> aten_inputs({t0, t1});

  FusionExecutorCache executor_cache(std::move(fusion));
  auto cg_outputs = executor_cache.runFusionWithInputs(aten_inputs);
}
```

```
unknown file: Failure
C++ exception with description "!(rparams.multiple_reds_per_blk && !has_iter_axis) INTERNAL ASSERT FAILED at "/raid/nmaruyama/debug1/nvfuser/csrc/scheduler/reduction_utils.cpp":58, please report a bug to PyTorch. Multiple reductions requires an iter domain, but one wasn't found.
Exception raised from scheduleReductionTV at /raid/nmaruyama/debug1/nvfuser/csrc/scheduler/reduction_utils.cpp:58 (most recent call first):
```
