### ISSUE TITLE
`define_scalar` input doesn't allow for type to be `Float`.

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#327]
Repro:

```
import torch
from nvfuser import FusionDefinition, DataType

def fusion(fd: FusionDefinition):
    t0 = fd.define_scalar(dtype=DataType.Float)
    t1 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguity=[True, True])
    t2 = fd.ops.add(t0, t1)
    fd.add_output(t2)

with FusionDefinition() as fd:
    fusion(fd)
```
Error:
```
Traceback (most recent call last):
  File "/workspace/test.py", line 10, in <module>
    with FusionDefinition() as fd:
  File "/opt/pytorch/pytorch/nvfuser/__init__.py", line 37, in __exit__
    self._finalize_definition()
RuntimeError: Dtype is not supported:float
```

**Comment by kevinstephano** [comment]
Closing as this issue was resolved with PR #208.
