### ISSUE TITLE
Segfault in NVFuser in Thunder container / CI

### ISSUE THREAD

**Issue by t-vi** [NVIDIA/Fuser#3291]
In the Thunder docker container (and thus in the CI), we're seeing crashes with NVFuser. I'm not quite sure why, but the following crashes in the container downloadable by
```
docker pull pytorchlightning/lightning-thunder:ubuntu22.04-cuda12.1.1-cudnn-fe1.5.2-py3.10-pt_main-dev
```

LMK if you need a build log for the nvfuser version in the container.

repro:
```python
#### # CUDA devices:
#  0: NVIDIA GeForce RTX 3090
#  1: NVIDIA GeForce RTX 3090
# torch version: 2.6.0a0+git279ddfc
# cuda version: 12.1
# nvfuser version: 0.2.17+gitd630e71
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id2(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, 4, 2, 8], contiguity=[None, True, False, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T1 = fd.define_tensor(shape=[1, 4, 2, 8], contiguity=[None, True, False, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T2 = fd.define_tensor(shape=[2, 16], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T3 = fd.define_tensor(shape=[1, 4, 2, 16], contiguity=[None, True, False, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T4 = fd.define_tensor(shape=[2, 16], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T5 = fd.define_tensor(shape=[1, 4, 2, 8], contiguity=[None, True, False, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T6 = fd.define_tensor(shape=[1, 4, 2, 8], contiguity=[None, True, False, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T7 = fd.define_tensor(shape=[1, 4, 2, 16], contiguity=[None, True, False, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T8 = fd.define_tensor(shape=[1, 4, 2, 0], contiguity=[None, True, False, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T9 = fd.define_tensor(shape=[1, 4, 2, 0], contiguity=[None, True, False, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T10 = fd.define_tensor(shape=[1, 4, 3, 16], contiguity=[None, True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T11 = fd.define_tensor(shape=[1, 4, 3, 16], contiguity=[None, True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T12 = fd.ops.neg(T0)
    T13 = fd.ops.cat([T12, T1], dim=-1)
    S14 = fd.define_scalar(1, dtype=DataType.Int)
    S15 = fd.define_scalar(4, dtype=DataType.Int)
    S16 = fd.define_scalar(2, dtype=DataType.Int)
    S17 = fd.define_scalar(16, dtype=DataType.Int)
    T19 = fd.ops.broadcast_in_dim(T2, shape=[S14, S15, S16, S17], broadcast_dims=[2, 3])
    T20 = fd.ops.mul(T3, T19)
    S21 = fd.define_scalar(1, dtype=DataType.Int)
    S22 = fd.define_scalar(4, dtype=DataType.Int)
    S23 = fd.define_scalar(2, dtype=DataType.Int)
    S24 = fd.define_scalar(16, dtype=DataType.Int)
    T26 = fd.ops.broadcast_in_dim(T4, shape=[S21, S22, S23, S24], broadcast_dims=[2, 3])
    T27 = fd.ops.mul(T13, T26)
    T28 = fd.ops.add(T20, T27)
    T29 = fd.ops.neg(T5)
    T30 = fd.ops.cat([T29, T6], dim=-1)
    T31 = fd.ops.mul(T7, T19)
    T32 = fd.ops.mul(T30, T26)
    T33 = fd.ops.add(T31, T32)
    T34 = fd.ops.cat([T28, T8], dim=-1)
    T35 = fd.ops.cat([T33, T9], dim=-1)
    T36 = fd.ops.set(T10)
    fd.add_output(T36, T11)
    fd.add_output(T34)
    fd.add_output(T35)
    fd.add_output(T11)

with FusionDefinition() as fd:
    nvfuser_fusion_id2(fd)

inputs = [
    torch.randn(344, dtype=torch.float32, device='cuda:0').as_strided((1, 4, 2, 8), (192, 48, 192, 1)),
    torch.randn(344, dtype=torch.float32, device='cuda:0').as_strided((1, 4, 2, 8), (192, 48, 192, 1)),
    torch.testing.make_tensor((2, 16), dtype=torch.float32, device='cuda:0'),
    torch.randn(352, dtype=torch.float32, device='cuda:0').as_strided((1, 4, 2, 16), (192, 48, 192, 1)),
    torch.testing.make_tensor((2, 16), dtype=torch.float32, device='cuda:0'),
    torch.randn(344, dtype=torch.float32, device='cuda:0').as_strided((1, 4, 2, 8), (192, 48, 192, 1)),
    torch.randn(344, dtype=torch.float32, device='cuda:0').as_strided((1, 4, 2, 8), (192, 48, 192, 1)),
    torch.randn(352, dtype=torch.float32, device='cuda:0').as_strided((1, 4, 2, 16), (192, 48, 192, 1)),
    torch.testing.make_tensor((1, 4, 2, 0), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 4, 2, 0), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 4, 3, 16), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 4, 3, 16), dtype=torch.float32, device='cuda:0'),
]
fd.execute(inputs)

```

Traceback:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007f973a78ac9d in __dynamic_cast () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007f973a78ac9d in __dynamic_cast () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f96775509f5 in nvfuser::preseg_passes::MovePadPass::runPass(nvfuser::Fusion*) () from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#2  0x00007f9677554d88 in nvfuser::preseg_passes::PreSegmenter::runPass(nvfuser::Fusion*) () from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#3  0x00007f96775b7185 in nvfuser::FusionKernelRuntime::FusionKernelRuntime(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::serde::FusionKernelRuntime const*, std::optional<nvfuser::PrimDataType>, long, long, long, bool) () from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#4  0x00007f96775ac045 in nvfuser::FusionExecutorCache::getKernelRuntimeFor(nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>) ()
   from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#5  0x00007f96775acae9 in nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) ()
   from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#6  0x00007f967771fcc6 in nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, std::optional<signed char>, bool, bool, bool) const ()
   from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#7  0x00007f9676f7922e in nvfuser::python_frontend::initNvFuserPythonBindings(_object*)::{lambda(nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, std::optional<long>, bool, bool, bool)#61}::operator()(nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, std::optional<long>, bool, bool, bool) const [clone .constprop.0] [clone .isra.0] ()
   from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#8  0x00007f9676ff861f in pybind11::cpp_function::initialize<nvfuser::python_frontend::initNvFuserPythonBindings(_object*)::{lambda(nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, std::optional<long>, bool, bool, bool)#61}, std::vector<at::Tensor, std::allocator<at::Tensor> >, nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, std::optional<long>, bool, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::kw_only, pybind11::arg_v, pybind11::arg_v, pybind11::arg_v, pybind11::arg_v, pybind11::return_value_policy>(nvfuser::python_frontend::initNvFuserPythonBindings(_object*)::{lambda(nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, std::optional<long>, bool, bool, bool)#61}&&, std::vector<at::Tensor, std::allocator<at::Tensor> > (*)(nvfuser::python_frontend::FusionDefinition&, pybind11::iterable const&, std::optional<long>, bool, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::kw_only const&, pybind11::arg_v const&, pybind11::arg_v const&, pybind11::arg_v const&, pybind11::arg_v const&, pybind11::return_value_policy const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) () from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#9  0x00007f967708d678 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /usr/local/lib/python3.10/dist-packages/nvfuser-0.2.17+gitd630e71-py3.10-linux-x86_64.egg/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
#10 0x000055df9a415b2e in ?? ()
#11 0x000055df9a40c2db in _PyObject_MakeTpCall ()
#12 0x000055df9a42455b in ?? ()
```

**Comment by t-vi** [comment]
Tentatively thinking it might just be a bad combination of git commits of PT and NVFuser, so I'm closing it for now.
