### ISSUE TITLE
Slice+Softmax fusion is triggering a scheduler error

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#40]
This is the error being triggered in dot-product attention that includes `slice` and `softmax`.  You can reproduce the issue with the following branch:  `add_py_slice_api_plus_codegen_fix`

Error output:

```
ERROR: test_nanogpt_slice (__main__.TestNvFuserFrontend)                                                                                                       
----------------------------------------------------------------------                                                                                         
Traceback (most recent call last):                                             
  File "/opt/pytorch/nvfuser/python_tests/test_python_frontend.py", line 1538, in test_nanogpt_slice                                                           
    out = fd.execute(inputs)                                                                                                                                   
  File "/opt/pytorch/pytorch/nvfuser/__init__.py", line 51, in execute                                                                                         
    return self._execute(inputs, override_user_schedule)                                                                                                       
RuntimeError: (int64_t)( num_blocks_per_SM * at::cuda::getDeviceProperties(options_.device.index()) ->multiProcessorCount) >= launch_params_.gdimx() * launch_params_.gdimy() * launch_params_.gdimz() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":1190, please report a bug to PyTorch. Wanted to laun
ch a cooperative kernel, however the number of blocks is greater than what can be resident on the GPU at once. Need: 32768 (32768 * 1 * 1) but limited to 4 * 108 
```

Test case:

```
    def test_nanogpt_slice(self) :
        inputs = [
            torch.randn(1, 1, 1024, 1204, device='cuda'),
            torch.randn(16, 16, 128, 128, device='cuda'),
        ]
        def nvfuser_fusion(fd : FusionDefinition) -> None :
            T0 = fd.define_tensor(symbolic_sizes=[1, 1, -1, -1], contiguous=[None, None, True, True], dtype=DataType.Float, is_cpu=False)
            T1 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguous=[True, True, True, True], dtype=DataType.Float, is_cpu=False)
            S1 = fd.define_constant(0.125000, dtype=DataType.Double)
            T2 = fd.ops.mul(T1, S1)
            T0_slice = fd.ops.slice(T0, [0, 0, 0, 0], [1, 1, 128, 128], [1, 1, 1, 1])
            S2 = fd.define_constant(0.00000, dtype=DataType.Double)
            T3 = fd.ops.eq(S2, T0_slice)
            T4 = fd.ops.broadcast_in_dim(T3, output_shape=[16, 16, 128, 128], broadcast_dims=[0, 1, 2, 3])
            S5 = fd.define_constant(float("-inf"), dtype=DataType.Double)
            T6 = fd.ops.where(T4, S5, T2)
            S7 = fd.define_constant(-1, dtype=DataType.Int)
            S8 = fd.define_constant(4, dtype=DataType.Int)
            S9 = fd.ops.add(S7, S8)
            T10 = fd.ops.max(T6, axes=[3], keepdim=False, dtype=DataType.Null)
            T11 = fd.ops.broadcast_in_dim(T10, output_shape=[16, 16, 128, 1], broadcast_dims=[0, 1, 2])
            T12 = fd.ops.broadcast_in_dim(T11, output_shape=[16, 16, 128, 128], broadcast_dims=[0, 1, 2, 3])
            T13 = fd.ops.sub(T6, T12)
            T14 = fd.ops.exp(T13)
            S15 = fd.define_constant(-1, dtype=DataType.Int)
            S16 = fd.define_constant(4, dtype=DataType.Int)
            S17 = fd.ops.add(S15, S16)
            T18 = fd.ops.sum(T14, axes=[3], keepdim=False, dtype=DataType.Null)
            T19 = fd.ops.broadcast_in_dim(T18, output_shape=[16, 16, 128, 1], broadcast_dims=[0, 1, 2])
            T20 = fd.ops.broadcast_in_dim(T19, output_shape=[16, 16, 128, 128], broadcast_dims=[0, 1, 2, 3])
            T21 = fd.ops.div(T14, T20)
            S22 = fd.define_constant(16, dtype=DataType.Int)
            S23 = fd.define_constant(16, dtype=DataType.Int)
            S24 = fd.define_constant(128, dtype=DataType.Int)
            S25 = fd.define_constant(128, dtype=DataType.Int)
            S26 = fd.define_constant(0.00000, dtype=DataType.Double)
            S27 = fd.define_constant(1.00000, dtype=DataType.Double)
            T28 = fd.ops.uniform(S26, S27, shape=[S22, S23, S24, S25], dtype=DataType.Float)
            S29 = fd.define_constant(0.900000, dtype=DataType.Double)
            T30 = fd.ops.lt(T28, S29)
            T31 = fd.ops.cast(T30, dtype=DataType.Float)
            T32 = fd.ops.mul(T21, T31)
            S33 = fd.define_constant(1.11111, dtype=DataType.Double)
            T34 = fd.ops.mul(T32, S33)
            fd.add_output(T34)
        with FusionDefinition() as fd:
            nvfuser_fusion(fd)
        out = fd.execute(inputs)
```

**Comment by kevinstephano** [comment]
This issue was fixed with Naoya's PR #28.
