### ISSUE TITLE
pad causes CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE

### ISSUE THREAD

**Issue by IvanYashchuk** [NVIDIA/Fuser#458]
Are these arguments to `pad` valid? It causes `CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE` (on 3080ti)
Here's a reproducer:
```py
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id6(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float, is_cpu=False)
    T1 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float, is_cpu=False)
    T2 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float, is_cpu=False)
    T3 = fd.ops.permute(T1, dims=[0, 1, 3, 2])
    T4 = fd.ops.permute(T2, dims=[0, 2, 1, 3])
    T5 = fd.ops.reshape(T4, original_shape=[8, 1024, 16, 64], new_shape=[8, 1024, 1024])
    T6 = fd.ops.permute(T0, dims=[0, 2, 1, 3])
    T7 = fd.ops.reshape(T6, original_shape=[8, 1024, 16, 64], new_shape=[8, 1024, 1024])
    T8 = fd.ops.permute(T3, dims=[0, 2, 1, 3])
    T9 = fd.ops.reshape(T8, original_shape=[8, 1024, 16, 64], new_shape=[8, 1024, 1024])
    S10 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T11 = fd.ops.pad(T5, [2048, 0, 0, 0, 0, 0], S10)
    S12 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T13 = fd.ops.pad(T9, [1024, 1024, 0, 0, 0, 0], S12)
    T14 = fd.ops.add(T11, T13)
    S15 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T16 = fd.ops.pad(T7, [0, 2048, 0, 0, 0, 0], S15)
    T17 = fd.ops.add(T14, T16)
    fd.add_output(T17)

with FusionDefinition() as fd:
    nvfuser_fusion_id6(fd)

inputs = [
    torch.randn((8, 16, 1024, 64), dtype=torch.float32, device='cuda:0').as_strided((8, 16, 1024, 64), (1048576, 65536, 64, 1)),
    torch.randn((8, 16, 64, 1024), dtype=torch.float32, device='cuda:0').as_strided((8, 16, 64, 1024), (1048576, 65536, 1024, 1)),
    torch.randn((8, 16, 1024, 64), dtype=torch.float32, device='cuda:0').as_strided((8, 16, 1024, 64), (1048576, 65536, 64, 1)),
]
fd.execute(inputs)
```

**Comment by naoyam** [comment]
I thought we could easily bail out for the case like this, but realized we don't have the necessary information at `canScheduleRuntime`. Basically we would need to know if resized or indexed domains would be parallelized by blockIdx, which would effectively mean we would also need to compute the heuristics parameters. We could of course extend `canSchedulerRuntime` to do so, but I'm feeling this would just become an ad-hoc WAR since the real problem is we are treating resized or indexed domains just like normal domains with only pointwise data dependency, which is not true, but that was convenient since it allows the existing schedulers to fuse them aggressively. I think we should treat them more like reduction domains, but we also don't want to have a new scheduler just for resize or index ops since then we would also need to create, for example, a different scheduler for fusions with resize and reduction ops, whereas in the current approach the reduction scheduler (opportunistically) fuses them together. 

Since I don't think there's any quick not-so-ugly WAR, I'm thinking that we would need to change the default behavior to require resize inputs to be fusion inputs with an opt-in option to lift the requirement. Same for take_along_axis.

**Comment by IvanYashchuk** [comment]
Another fusion definition, now with `take_along_axis` that fails on A100:
```py
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id6(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    T1 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguity=[True, True], dtype=DataType.Int, is_cpu=False)
    T2 = fd.ops.reshape(T0, original_shape=[16, 128, 50257], new_shape=[2048, 50257])
    T3 = fd.ops.reshape(T1, original_shape=[16, 128], new_shape=[2048])
    T4 = fd.ops.max(T2, axes=[1], keepdim=False, dtype=DataType.Null)
    T5 = fd.ops.broadcast_in_dim(T4, output_shape=[2048, 1], broadcast_dims=[0])
    T6 = fd.ops.broadcast_in_dim(T5, output_shape=[2048, 50257], broadcast_dims=[0, 1])
    T7 = fd.ops.sub(T2, T6)
    T8 = fd.ops.exp(T7)
    T9 = fd.ops.sum(T8, axes=[1], keepdim=False, dtype=DataType.Null)
    T10 = fd.ops.broadcast_in_dim(T9, output_shape=[2048, 1], broadcast_dims=[0])
    T11 = fd.ops.log(T10)
    T12 = fd.ops.broadcast_in_dim(T11, output_shape=[2048, 50257], broadcast_dims=[0, 1])
    T13 = fd.ops.sub(T7, T12)
    T14 = fd.ops.neg(T13)
    T15 = fd.ops.reshape(T3, original_shape=[2048], new_shape=[2048, 1])
    T16 = fd.ops.take_along_axis(T14, T15, dim=1)
    T17 = fd.ops.sum(T16, axes=[0, 1], keepdim=False, dtype=DataType.Null)
    S18 = fd.define_scalar(2048.00, dtype=DataType.Double)
    S19 = fd.ops.reciprocal(S18)
    T20 = fd.ops.mul(T17, S19)
    fd.add_output(T20)

with FusionDefinition() as fd:
    nvfuser_fusion_id6(fd)

inputs = [
    torch.randn((16, 128, 50257), dtype=torch.float32, device='cuda:0').as_strided((16, 128, 50257), (6432896, 50257, 1)),
    torch.randint(0, 10, (16, 128), dtype=torch.int64, device='cuda:0').as_strided((16, 128), (128, 1)),
]
fd.execute(inputs)
```

**Comment by jjsjann123** [comment]
It does repro with sizes below even on my old cross_entropy script. So it's likely a heuristic issue here.
```
inputs = [
    torch.randn((16, 128, 50257), dtype=torch.float32, device='cuda:0').as_strided((16, 128, 50257), (6432896, 50257, 1)),
    torch.randint(0, 10, (16, 128), dtype=torch.int64, device='cuda:0').as_strided((16, 128), (128, 1)),
]
```

```
Traceback (most recent call last):
  File "/jiej/lightning-thunder/thunder/__init__.py", line 394, in _fn
    result = c(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "LC.gen", line 8, in thunder_140084115359440
  File "/jiej/lightning-thunder/thunder/executors/nvfuser.py", line 1459, in fn_
    return fd.execute(args)
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 109, in execute
    result = self._execute(inputs, override_user_schedule, device=device)
RuntimeError: _result == CUDA_SUCCESS INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":1780, please report a bug to PyTorch. CUDA error: CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE failed with error too many blocks in cooperative launch
```

cc'ing @naoyam

**Comment by naoyam** [comment]
This is the same issue as I mentioned last week. I'll disable this type of fusions to avoid the error. I think we can still keep it working without an opt-in option for small sizes. Will work on it today.

**Comment by IvanYashchuk** [comment]
Is there a PR for disabling this type of fusion?

**Comment by IvanYashchuk** [comment]
@naoyam, was this fusion disabled?

Another similar example hitting the same error: 
```py
from nvfuser import FusionDefinition, DataType
import torch

t19 = torch.randn(8, 16, 1024, 64, device="cuda", dtype=torch.float32)
t21 = torch.randn(8, 16, 64, 1024, device="cuda", dtype=torch.float32)
t17 = torch.randn(8, 16, 1024, 64, device="cuda", dtype=torch.float32)

def nvfuser_fusion_id2(fd : FusionDefinition) -> None :
    t21 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float)
    t17 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float)
    t19 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float)
    t22 = fd.ops.permute(t21, [0, 1, 3, 2])
    t23 = fd.ops.permute(t17, [0, 2, 1, 3])
    t24 = fd.ops.reshape(t23, original_shape=[8, 1024, 16, 64], new_shape=[8, 1024, 1024])
    t25 = fd.ops.permute(t19, [0, 2, 1, 3])
    t26 = fd.ops.reshape(t25, original_shape=[8, 1024, 16, 64], new_shape=[8, 1024, 1024])
    t27 = fd.ops.permute(t22, [0, 2, 1, 3])
    t28 = fd.ops.reshape(t27, original_shape=[8, 1024, 16, 64], new_shape=[8, 1024, 1024])
    S3 = fd.define_scalar(0.00000, dtype=DataType.Double)
    t29 = fd.ops.pad(t24, [2048, 0, 0, 0, 0, 0], S3)
    S5 = fd.define_scalar(0.00000, dtype=DataType.Double)
    t30 = fd.ops.pad(t28, [1024, 1024, 0, 0, 0, 0], S5)
    t31 = fd.ops.add(t29, t30)
    S8 = fd.define_scalar(0.00000, dtype=DataType.Double)
    t32 = fd.ops.pad(t26, [0, 2048, 0, 0, 0, 0], S8)
    t33 = fd.ops.add(t31, t32)
    fd.add_output(t33)

with FusionDefinition() as nvFusion2:
    nvfuser_fusion_id2(nvFusion2)

out = nvFusion2.execute([t21, t17, t19])
```

**Comment by naoyam** [comment]
@IvanYashchuk I'm closing as it shouldn't fail anymore. Let me know otherwise.

**Comment by IvanYashchuk** [comment]
All of the above examples are now working. Thank you!
