### ISSUE TITLE
TorchScript test in CI is failing

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/Fuser#510]
See for example: https://github.com/NVIDIA/Fuser/actions/runs/5341204474/jobs/9681800392
```python
******** JOB LOGS with sensitive data redacted ************** 

# Failed tests (if any)
### [jit_python_tests_V[10](https://github.com/NVIDIA/Fuser/actions/runs/5341204474/jobs/9681800392#step:2:11)0] TestCudaFuser.test_alias_pass_fix

Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/python_tests/test_torchscript.py", line 4855, in test_alias_pass_fix
    self._run_helper(t_jit, t, x, w, b)
  File "/opt/pytorch/nvfuser/python_tests/test_torchscript.py", line 270, in _run_helper
    self.assertGraphContainsExactly(
  File "/opt/pytorch/pytorch/torch/testing/_internal/jit_utils.py", line 325, in assertGraphContainsExactly
    perform_assert(graph, kind, count, num_kind_nodes,
  File "/opt/pytorch/pytorch/torch/testing/_internal/jit_utils.py", line 318, in perform_assert
    raise AssertionError(
AssertionError: graph(%x.1 : Tensor,
      %w.1 : Tensor,
      %b.1 : Tensor):
  %3 : float = prim::Constant[value=1.]() # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:4850:21
  %4 : int = prim::Constant[value=1]()
  %5 : int[] = prim::Constant[value=[1, 1]]()
  %6 : int[] = prim::Constant[value=[0, 0]]()
  %b2.1 : Tensor = aten::add(%b.1, %3, %4) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:4850:17
  %o.1 : Tensor = aten::conv2d(%x.1, %w.1, %b2.1, %5, %6, %5, %4) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:4851:16
  return (%o.1)

Error: graph contains 0 prim::CudaFusionGuard nodes (including subgraphs) but expected 1




### [jit_python_tests_V100] TestCudaFuser.test_conv2d_bias

Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/python_tests/test_torchscript.py", line 4[12](https://github.com/NVIDIA/Fuser/actions/runs/5341204474/jobs/9681800392#step:2:13)9, in test_conv2d_bias
    self.assertGraphContains(graph, FUSION_GROUP, True)
  File "/opt/pytorch/pytorch/torch/testing/_internal/jit_utils.py", line 298, in assertGraphContains
    self.assertTrue(count > 0)
AssertionError: False is not true




### [jit_python_tests_V100] TestCudaFuser.test_linear

Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/python_tests/test_torchscript.py", line 3293, in test_linear
    self._run_helper(
  File "/opt/pytorch/nvfuser/python_tests/test_torchscript.py", line 270, in _run_helper
    self.assertGraphContainsExactly(
  File "/opt/pytorch/pytorch/torch/testing/_internal/jit_utils.py", line 325, in assertGraphContainsExactly
    perform_assert(graph, kind, count, num_kind_nodes,
  File "/opt/pytorch/pytorch/torch/testing/_internal/jit_utils.py", line 318, in perform_assert
    raise AssertionError(
AssertionError: graph(%x.1 : Tensor,
      %weight.1 : Tensor,
      %bias.1 : Tensor):
  %o.1 : Tensor = aten::linear(%x.1, %weight.1, %bias.1) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:3276:[16](https://github.com/NVIDIA/Fuser/actions/runs/5341204474/jobs/9681800392#step:2:17)
  %o.5 : Tensor = aten::relu(%o.1) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:3[27](https://github.com/NVIDIA/Fuser/actions/runs/5341204474/jobs/9681800392#step:2:28)7:16
  return (%o.5)

Error: graph contains 0 prim::CudaFusionGuard nodes (including subgraphs) but expected 1




### [jit_python_tests_V100] TestCudaFuser.test_index_select_shape_expression

Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/python_tests/test_torchscript.py", line 4954, in test_index_select_shape_expression
    FileCheck().check("prim::infer_index_select_size").run(g)
RuntimeError: Expected to find "prim::infer_index_select_size" but did not find it
Searched string:
graph(%x.1 : Tensor,
~~~~~~~~~~~~~~~~~~~~
      %y.1 : Tensor,
      ~~ <--- HERE
      %ind.1 : Tensor):
  %3 : int = prim::Constant[value=0]() # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:4946:[38](https://github.com/NVIDIA/Fuser/actions/runs/5341204474/jobs/9681800392#step:2:39)
From CHECK: prim::infer_index_select_size
```

**Comment by zasdfgbnm** [comment]
cc: @jjsjann123

**Comment by jjsjann123** [comment]
Looks like #498 breaks the env set for python test.

**Comment by zasdfgbnm** [comment]
Fixed in https://github.com/NVIDIA/Fuser/pull/513
