### ISSUE TITLE
Detect when CUDA Graph capture is ongoing at the time of kernel compilation or loading

### ISSUE THREAD

**Issue by IvanYashchuk** [NVIDIA/Fuser#635]
Here's a way to trigger a CUDA error of not permitted operation during graph capturing. It would be great to detect that the CUDA graph capture is ongoing before we try to load/compile kernels and error out with a better error message.

```py
import torch
from nvfuser import FusionDefinition, DataType

with FusionDefinition() as fd:
    T1 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False)
    T2 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False)
    T3 = fd.ops.add(T1, T2)
    fd.add_output(T3)

t1 = torch.randn(10, device="cuda")
t2 = torch.randn(10, device="cuda")

torch.cuda.synchronize()
stream = torch.cuda.Stream()
stream.wait_stream(torch.cuda.current_stream())
stream.synchronize()
torch.cuda.current_stream().wait_stream(stream)
torch.cuda.synchronize()

# Skipping warmup going straight to CUDA graph capture
graph = torch.cuda.CUDAGraph()
with torch.cuda.graph(graph, stream=stream):
    out = fd.execute([t1, t2])

torch.cuda.synchronize()
```
error:
```py
An error occurred while executing nvFuser FusionDefinition 0.
If you believe this is a bug or need assistance, please file an issue at https://github.com/NVIDIA/Fuser/issues/new
Here's a script to reproduce the error:
```
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False)
    T1 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False)
    T2 = fd.ops.add(T0, T1)
    fd.add_output(T2)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.randn((10,), dtype=torch.float32, device='cuda:0').as_strided((10,), (1,)),
    torch.randn((10,), dtype=torch.float32, device='cuda:0').as_strided((10,), (1,)),
]
fd.execute(inputs)
```
Traceback (most recent call last):
  File "/home/iyashchuk/dev/pytorch/master/nvfuser/__init__.py", line 111, in execute
    result = self._execute(inputs, override_user_schedule, device=device)
RuntimeError: _result == CUDA_SUCCESS INTERNAL ASSERT FAILED at "/home/iyashchuk/dev/nvfuser/csrc/executor_utils.cpp":1124, please report a bug to PyTorch. CUDA error: CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED failed with error operation not permitted when stream is capturing
```

**Comment by pulver** [comment]
Is this still an issue? Running the above test results in
```
$ python test_nvfuser.py
Traceback (most recent call last):
  File "test_nvfuser.py", line 5, in <module>
    T1 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: define_tensor(): incompatible function arguments. The following argument types are supported:
    1. (self: nvfuser._C._FusionDefinition, shape: list[int], contiguity: list[Optional[bool]], dtype: nvfuser._C.DataType = <DataType.Float: 1>, is_cpu: bool = False, stride_order: list[int] = []) -> nvfuser._C.Tensor
    2. (self: nvfuser._C._FusionDefinition, shape: list[int], contiguity: bool = False, dtype: nvfuser._C.DataType = <DataType.Float: 1>, is_cpu: bool = False, stride_order: list[int] = []) -> nvfuser._C.Tensor
    3. (self: nvfuser._C._FusionDefinition, sizes: list[int], strides: list[int], dtype: nvfuser._C.DataType = <DataType.Float: 1>, static_sizes: bool = False, is_cpu: bool = False) -> nvfuser._C.Tensor

Invoked with: 
def nvfuser_incomplete_fusion(fd : FusionDefinition) -> None :

; kwargs: symbolic_sizes=[-1], contiguity=[True], dtype=<DataType.Float: 1>, is_cpu=False
```
As a guess I replaced `symbolic_sizes` with `shape` which runs successfully with no output and returns code 0.

Am I missing something, or is there a better way to fix the test to reproduce the bug?
